/* MYTHOS Control Center — Projects: the list, the short project form (new /
   edit) and the project page: Overview · WhatsApp · AI · Catalogue (Auto
   only) · Members · Advanced. The slug is generated by the server. */
import { h, clear, badge, fmtDate, skeletonRows, errorBox, empty, toast, tabs, chip, kv, pageHead, simpleTable, switchInput, drawer, confirmDialog, qget, setQuery, roleNote, json, details, fmtMasked, connBadge } from '../ui.js';
import { routingPanel } from './whatsapp.js';
import { agentsPanel, runsPanel } from './ai.js';
import { integrationsPanel, automationsPanel, auditPanel } from './settings.js';
import { usersPanel } from './settings.js';
import { loadNumbers, loadAgents, linksOf, agentOf, summarize, aiWords } from '../data.js';

const TYPES = [{ value: 'service', label: 'Service' }, { value: 'automotive', label: 'Auto' }, { value: 'internal', label: 'Internal' }];
function typeLabel(kind) { const t = TYPES.find((x) => x.value === kind); return t ? t.label : (kind || 'Service'); }
function aiBadge(mode) { return badge(aiWords(mode), mode === 'auto' ? 'ok' : mode === 'suggest' ? 'info' : 'mock'); }

/* ── List ─────────────────────────────────────────────────────────────── */
export async function render(main, params, query, ctx) {
  ctx.crumbs([{ label: 'Projects' }]);
  main.appendChild(pageHead(null, 'Projects', null, [ctx.can('admin') ? h('a', { class: 'btn btn-primary', href: '#/projects/new' }, 'New project') : null]));
  const box = h('div', {}, skeletonRows(3)); main.appendChild(box);
  const [dash, numbers, agents] = await Promise.all([ctx.api.get('/api/dashboard?project=all').then((d) => (d.projects && d.projects.activity) || [], () => []), loadNumbers(), loadAgents()]);
  clear(box);
  const rows = ctx.projects().map((p) => Object.assign({}, p, { summary: summarize(dash.find((a) => a.id === p.id), numbers, agents, p.id) }));
  if (!rows.length) { box.appendChild(empty('No project', 'Create the first project.', ctx.can('admin') ? h('a', { class: 'btn btn-primary', href: '#/projects/new' }, 'New project') : null)); return; }
  box.appendChild(simpleTable([
    { label: 'Name', cell: (p) => h('a', { href: '#/projects/' + encodeURIComponent(p.id) }, h('strong', {}, p.display_name)) },
    { label: 'Type', cell: (p) => typeLabel(p.kind) },
    { label: 'Status', cell: (p) => badge(p.status) },
    { label: 'WhatsApp', cell: (p) => p.summary.whatsapp.length ? h('div', { class: 'stack xs' }, p.summary.whatsapp.map((n) => h('span', { class: 'num-line' }, h('span', { class: 'mono' }, fmtMasked(n.phone_masked)), ' ', connBadge(n.status)))) : h('span', { class: 'dim' }, 'No number') },
    { label: 'AI', cell: (p) => p.summary.ai.agent ? h('span', {}, p.summary.ai.agent, ' ', aiBadge(p.summary.ai.mode)) : h('span', { class: 'dim' }, 'No agent') }
  ], rows, { noScroll: true, onRow: (p) => { location.hash = '#/projects/' + encodeURIComponent(p.id); } }));
}

/* ── Short form: #/projects/new and #/projects/:id/edit ───────────────── */
export async function renderForm(main, params, query, ctx) {
  const editing = !!params.id;
  if (!ctx.can('admin')) { main.appendChild(empty('Not allowed', 'Creating or editing a project requires the admin role.')); return; }
  let row = null;
  if (editing) { try { row = (await ctx.api.get('/api/r/projects/' + encodeURIComponent(params.id))).row; } catch (err) { main.appendChild(errorBox(err)); return; } }
  ctx.crumbs([{ label: 'Projects', href: '#/projects' }].concat(editing ? [{ label: row.display_name, href: '#/projects/' + encodeURIComponent(row.id) }, { label: 'Edit' }] : [{ label: 'New project' }]));
  main.appendChild(pageHead(null, editing ? 'Edit ' + row.display_name : 'New project'));
  const [numbers, agents] = editing ? [[], []] : await Promise.all([loadNumbers(), loadAgents()]);
  const c = {};
  const field = (label, ctrl, req, hint) => h('div', { class: 'field' }, h('label', { for: ctrl.id }, label, req ? h('span', { class: 'req' }, ' *') : null), ctrl, hint ? h('span', { class: 'hint' }, hint) : null);
  c.name = h('input', { class: 'input', id: 'p-name', maxlength: 128, autocomplete: 'off' }); c.name.value = row ? row.display_name : '';
  const presetKind = TYPES.some((t) => t.value === qget(query, 'type')) ? qget(query, 'type') : 'service';
  c.kind = h('select', { class: 'select', id: 'p-kind' }, TYPES.map((t) => h('option', { value: t.value, selected: (row ? row.kind : presetKind) === t.value || undefined }, t.label)));
  c.brand = h('input', { class: 'input', id: 'p-brand', maxlength: 64, placeholder: 'e.g. SsangYong' }); c.brand.value = row && row.brand_car ? row.brand_car : '';
  c.domain = h('input', { class: 'input', id: 'p-domain', maxlength: 128, placeholder: 'example.tn' }); c.domain.value = row && row.domain ? row.domain : '';
  c.number = h('select', { class: 'select', id: 'p-number' }, h('option', { value: '' }, 'None'), numbers.map((n) => h('option', { value: String(n.id) }, fmtMasked(n.phone_masked) + ' · ' + (n.display_name || n.instance))));
  c.agent = h('select', { class: 'select', id: 'p-agent' }, h('option', { value: '' }, 'None'), agents.filter((a) => a.status !== 'archived').map((a) => h('option', { value: String(a.id) }, a.name)));
  c.description = h('textarea', { class: 'textarea', id: 'p-desc', rows: 3, maxlength: 4000 }); c.description.value = row && row.description ? row.description : '';
  c.currency = h('input', { class: 'input mono', id: 'p-currency', maxlength: 3 }); c.currency.value = row && row.currency ? row.currency : 'TND';
  const brandField = field('Vehicle brand', c.brand);
  const autoNote = h('span', { class: 'hint' }, 'The MYTHOS Auto Kitchen (parts, vehicles, prices) is attached automatically.');
  function syncKind() { const auto = c.kind.value === 'automotive'; brandField.hidden = !auto; autoNote.hidden = !auto; }
  c.kind.onchange = syncKind; syncKind();
  const err = h('p', { class: 'error', role: 'alert', hidden: true });
  const submit = h('button', { class: 'btn btn-primary', type: 'submit' }, editing ? 'Save' : 'Create project');
  const form = h('form', { class: 'short-form', novalidate: true, autocomplete: 'off' },
    field('Project name', c.name, true),
    h('div', { class: 'field-row' }, field('Type', c.kind, true), brandField),
    autoNote,
    field('Domain', c.domain),
    editing ? null : h('div', { class: 'field-row' }, field('WhatsApp', c.number, false, 'Optional. More numbers can be linked later.'), field('AI agent', c.agent, false, 'Optional.')),
    field('Description', c.description),
    field('Currency', c.currency),
    err,
    h('div', { class: 'view-actions' }, submit, h('a', { class: 'btn btn-secondary', href: editing ? '#/projects/' + encodeURIComponent(row.id) : '#/projects' }, 'Cancel')));
  form.addEventListener('submit', async (e) => {
    e.preventDefault(); err.hidden = true;
    const name = c.name.value.trim();
    if (!name) { err.textContent = 'Project name is required.'; err.hidden = false; c.name.focus(); return; }
    const currency = c.currency.value.trim().toUpperCase() || 'TND';
    if (!/^[A-Z]{3}$/.test(currency)) { err.textContent = 'Currency is a 3-letter code (TND, EUR…).'; err.hidden = false; c.currency.focus(); return; }
    const auto = c.kind.value === 'automotive';
    const body = { name, kind: c.kind.value, domain: c.domain.value.trim() || null, description: c.description.value.trim() || null, currency, brand_car: auto ? (c.brand.value.trim() || null) : null };
    submit.disabled = true;
    try {
      if (editing) {
        await ctx.api.patch('/api/r/projects/' + encodeURIComponent(row.id), { display_name: name, kind: body.kind, domain: body.domain, description: body.description, currency, brand_car: body.brand_car });
        toast('Project saved', 'ok'); await ctx.refreshMeta(); location.hash = '#/projects/' + encodeURIComponent(row.id); return;
      }
      body.phone_number_id = c.number.value ? Number(c.number.value) : null;
      body.agent_id = c.agent.value ? Number(c.agent.value) : null;
      let out;
      try { out = await ctx.api.post('/api/projects', body); }
      catch (e2) { if (e2.status !== 404) throw e2; out = await createLegacy(ctx, body); }
      const id = out && out.project ? out.project.id : (out && out.id);
      (out && out.warnings || []).forEach((w) => toast(typeof w === 'string' ? w : JSON.stringify(w), 'warn', 6000));
      toast('Project created', 'ok'); await ctx.refreshMeta(); location.hash = '#/projects/' + encodeURIComponent(id);
    } catch (e3) { err.textContent = (e3 && (e3.detail || e3.message)) || 'Save failed.'; if (e3 && e3.errors) err.textContent += ' ' + Object.keys(e3.errors).map((k) => k + ': ' + e3.errors[k]).join(', '); err.hidden = false; }
    finally { submit.disabled = false; }
  });
  main.appendChild(h('div', { class: 'card narrow' }, form));
  c.name.focus();
}

/* Until POST /api/projects exists: the same result through the generic resource + link/bind calls. */
async function createLegacy(ctx, body) {
  let slug = body.name.normalize('NFKD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48);
  if (!/^[a-z0-9]/.test(slug)) slug = 'p-' + slug;
  if (slug.length < 2) slug += '-project';
  const taken = ctx.projects().map((p) => p.id);
  let id = slug; for (let i = 2; taken.includes(id); i++) id = slug + '-' + i;
  const settings = body.kind === 'automotive' ? { kitchen: 'kitchen-mythos-auto' } : {};
  const o = await ctx.api.post('/api/r/projects', { id, display_name: body.name, kind: body.kind, status: 'active', domain: body.domain, description: body.description, currency: body.currency, brand_car: body.brand_car, settings });
  const warnings = [];
  if (body.phone_number_id) { try { await ctx.api.post('/api/whatsapp/numbers/' + body.phone_number_id + '/projects', { project_id: id, account_mode: 'dedicated' }); } catch (e) { warnings.push('The number could not be linked: ' + (e.detail || e.message)); } }
  if (body.agent_id) { try { await ctx.api.post('/api/ai/agents/' + body.agent_id + '/projects', { project_id: id }); } catch (e) { warnings.push('The agent could not be bound: ' + (e.detail || e.message)); } }
  return { project: o.row, warnings };
}

/* ── Project page ─────────────────────────────────────────────────────── */
const TABS = [{ key: 'overview', label: 'Overview' }, { key: 'whatsapp', label: 'WhatsApp' }, { key: 'ai', label: 'AI' }, { key: 'catalogue', label: 'Catalogue' }, { key: 'members', label: 'Members' }, { key: 'advanced', label: 'Advanced' }];

export async function renderOne(main, params, query, ctx) {
  const id = params.id;
  ctx.crumbs([{ label: 'Projects', href: '#/projects' }, { label: id }]);
  const box = h('div', { class: 'stack' }, skeletonRows(4)); main.appendChild(box);
  let row;
  try { row = (await ctx.api.get('/api/r/projects/' + encodeURIComponent(id))).row; } catch (err) { clear(box); box.appendChild(errorBox(err)); return; }
  clear(box);
  ctx.crumbs([{ label: 'Projects', href: '#/projects' }, { label: row.display_name }]);
  const automotive = (row.kind || 'service') === 'automotive';
  const tabList = TABS.filter((t) => t.key !== 'catalogue' || automotive);
  let tab = qget(query, 'tab', 'overview'); if (tab === 'numbers') tab = 'whatsapp'; if (tab === 'agents' || tab === 'settings' || tab === 'integrations' || tab === 'audit') tab = tab === 'agents' ? 'ai' : 'advanced'; if (!tabList.some((t) => t.key === tab)) tab = 'overview';
  main.insertBefore(pageHead(null, row.display_name, typeLabel(row.kind) + (row.domain ? ' · ' + row.domain : ''), [badge(row.status), h('button', { class: 'btn btn-secondary', type: 'button', onClick: () => { ctx.setProject(row.id); location.hash = '#/inbox'; } }, 'Open inbox')]), box);
  const bar = tabs(tabList, tab, (k) => { tab = k; setQuery('#/projects/' + encodeURIComponent(id), { tab: k }); show(); });
  box.appendChild(bar.el);
  const body = h('div', { class: 'tab-body' }); box.appendChild(body);
  function show() {
    clear(body);
    if (tab === 'overview') body.appendChild(overview(ctx, row));
    else if (tab === 'whatsapp') body.appendChild(whatsappTab(ctx, row));
    else if (tab === 'ai') body.appendChild(aiTab(ctx, row));
    else if (tab === 'catalogue') body.appendChild(catalogueTab(ctx, row));
    else if (tab === 'members') body.appendChild(usersPanel(ctx, { project: row.id }));
    else if (tab === 'advanced') body.appendChild(advancedTab(ctx, row));
  }
  show();
}

function overview(ctx, row) {
  const root = h('div', { class: 'stack' });
  const wa = h('span', { class: 'dim' }, 'Loading…'); const ai = h('span', { class: 'dim' }, 'Loading…');
  root.appendChild(h('div', { class: 'card' }, h('div', { class: 'card-head' }, h('h3', {}, 'Project'), ctx.can('admin') ? h('a', { class: 'btn btn-secondary btn-sm', href: '#/projects/' + encodeURIComponent(row.id) + '/edit' }, 'Edit') : null),
    kv([['Name', row.display_name], ['Type', typeLabel(row.kind)], ['Domain', row.domain], ['Status', badge(row.status)], ['Description', row.description], ['WhatsApp', wa], ['AI', ai]])));
  Promise.all([loadNumbers(), loadAgents(), ctx.api.get('/api/projects/' + encodeURIComponent(row.id) + '/ai').catch(() => null)]).then(([numbers, agents, aiCfg]) => {
    const links = linksOf(numbers, row.id);
    clear(wa); wa.className = '';
    if (!links.length) wa.appendChild(h('span', { class: 'dim' }, 'No number linked'));
    else wa.appendChild(h('div', { class: 'stack xs' }, links.map((x) => h('span', { class: 'num-line' }, h('span', { class: 'mono' }, fmtMasked(x.number.phone_masked)), ' ', connBadge(x.number)))));
    const s = aiCfg && aiCfg.agent ? { agent: typeof aiCfg.agent === 'object' ? aiCfg.agent.name : aiCfg.agent, mode: aiCfg.mode } : (() => { const a = agentOf(agents, row.id); return a ? { agent: a.name, mode: a.mode } : null; })();
    clear(ai); ai.className = '';
    ai.appendChild(s ? h('span', {}, s.agent, ' ', aiBadge(s.mode)) : h('span', { class: 'dim' }, 'No agent'));
  });
  return root;
}

/* ── WhatsApp tab: links of this project with switches, link / unlink ── */
function whatsappTab(ctx, row) {
  const root = h('div', { class: 'stack' });
  const admin = ctx.can('admin');
  const box = h('div', {}); root.appendChild(box);
  async function load() {
    clear(box); box.appendChild(skeletonRows(3));
    const numbers = await loadNumbers();
    clear(box);
    const links = linksOf(numbers, row.id);
    const free = numbers.filter((n) => !(n.projects || []).some((l) => l.project_id === row.id));
    const table = links.length ? simpleTable([
      { label: 'Number', cell: (x) => h('div', {}, h('strong', { class: 'mono' }, fmtMasked(x.number.phone_masked)), h('div', { class: 'dim small' }, x.link.inbox_display_name || x.number.display_name || '')) },
      { label: 'Connection', cell: (x) => connBadge(x.number) },
      { label: 'Receiving', stop: true, cell: (x) => switchInput({ checked: x.link.inbound_enabled, disabled: !admin, small: true, onChange: (v) => patch(x, { inbound_enabled: v }) }) },
      { label: 'Replies', stop: true, cell: (x) => switchInput({ checked: x.link.outbound_enabled, disabled: !admin, small: true, onChange: (v) => patch(x, { outbound_enabled: v }) }) },
      { label: 'AI', stop: true, cell: (x) => switchInput({ checked: (x.link.ai_mode || 'inherit') !== 'off', disabled: !admin, small: true, onChange: (v) => patch(x, { ai_mode: v ? 'inherit' : 'off' }) }) },
      { label: '', stop: true, cell: (x) => admin ? h('button', { class: 'btn btn-ghost btn-sm danger', type: 'button', onClick: async () => { if (!await confirmDialog({ title: 'Unlink ' + fmtMasked(x.number.phone_masked) + '?', body: 'Messages on this number stop reaching this project. Refused while conversations exist on it.', confirmLabel: 'Unlink', danger: true })) return; try { await ctx.api.del('/api/whatsapp/numbers/' + x.number.id + '/projects/' + x.link.inbox_id); toast('Unlinked', 'ok'); load(); } catch (err) { toast(err.status === 409 ? 'Refused: conversations exist on this number.' : (err.detail || 'Unlink failed.'), 'danger', 5000); } } }, 'Unlink') : null }
    ], links, { noScroll: true }) : empty('No number linked', 'Link a WhatsApp number so this project receives messages.');
    box.appendChild(table);
    if (admin) {
      const sel = h('select', { class: 'select', 'aria-label': 'Number to link' }, h('option', { value: '' }, free.length ? 'Choose a number…' : 'No free number'), free.map((n) => h('option', { value: String(n.id) }, fmtMasked(n.phone_masked) + ' · ' + (n.display_name || n.instance))));
      const btn = h('button', { class: 'btn btn-secondary', type: 'button', disabled: !free.length || undefined, onClick: async () => { if (!sel.value) return; btn.disabled = true; try { await ctx.api.post('/api/whatsapp/numbers/' + sel.value + '/projects', { project_id: row.id, account_mode: 'dedicated' }); toast('Number linked', 'ok'); load(); } catch (err) { toast(err.detail || 'Link failed.', 'danger', 5000); btn.disabled = false; } } }, 'Link a number');
      box.appendChild(h('div', { class: 'toolbar link-row' }, sel, btn));
    } else box.appendChild(roleNote(ctx, 'admin', 'Linking numbers'));
  }
  function patch(x, b) { return ctx.api.patch('/api/projects/' + row.id + '/inboxes/' + x.link.inbox_id, b).then(() => { Object.assign(x.link, b); toast('Saved', 'ok', 1800); }); }
  load();
  return root;
}

/* ── AI tab: one agent, one mode, one status, a test box ─────────────── */
function aiTab(ctx, row) {
  const root = h('div', { class: 'stack' });
  const admin = ctx.can('admin'), manager = ctx.can('manager');
  const box = h('div', { class: 'card narrow' }, skeletonRows(3)); root.appendChild(box);
  const pbase = '/api/projects/' + encodeURIComponent(row.id) + '/ai';
  let native = true;
  async function read() {
    try { return await ctx.api.get(pbase); }
    catch (err) {
      if (err.status !== 404) throw err;
      native = false;
      const agents = await loadAgents();
      const a = agentOf(agents, row.id);
      return { agent: a ? { id: a.id, name: a.name } : null, mode: a ? a.mode : 'off', status: a ? (a.status === 'active' ? 'active' : 'disabled') : 'disabled', agents: agents.filter((x) => x.status !== 'archived').map((x) => ({ id: x.id, name: x.name })) };
    }
  }
  async function load() {
    let cfg;
    try { cfg = await read(); } catch (err) { clear(box); box.appendChild(errorBox(err, load)); return; }
    clear(box);
    const curId = cfg.agent ? (typeof cfg.agent === 'object' ? cfg.agent.id : cfg.agent) : '';
    const choices = cfg.agents || [];
    const agentSel = h('select', { class: 'select', id: 'ai-agent', disabled: !admin || undefined }, h('option', { value: '' }, 'None'), choices.map((a) => h('option', { value: String(a.id), selected: String(a.id) === String(curId) || undefined }, a.name || ('#' + a.id))));
    const modeSel = h('select', { class: 'select', id: 'ai-mode', disabled: !admin || undefined }, [['off', 'Off — the AI never answers'], ['suggest', 'Suggest — the AI proposes, a human sends'], ['auto', 'Auto — the AI answers when it is sure']].map(([v, l]) => h('option', { value: v, selected: (cfg.mode || 'off') === v || undefined }, l)));
    const statusSel = h('select', { class: 'select', id: 'ai-status', disabled: !admin || undefined }, [['active', 'Active'], ['disabled', 'Disabled']].map(([v, l]) => h('option', { value: v, selected: (cfg.status || 'active') === v || undefined }, l)));
    const save = h('button', { class: 'btn btn-primary', type: 'button', disabled: !admin || undefined, onClick: async () => {
      save.disabled = true;
      const body = { agent_id: agentSel.value ? Number(agentSel.value) : null, mode: modeSel.value, status: statusSel.value };
      try {
        if (native) await ctx.api.put(pbase, body);
        else {
          if (body.agent_id) {
            const agents = await loadAgents(); const a = agents.find((x) => x.id === body.agent_id);
            if (a && !(a.projects || []).some((l) => l.project_id === row.id)) await ctx.api.post('/api/ai/agents/' + a.id + '/projects', { project_id: row.id });
            await ctx.api.patch('/api/ai/agents/' + body.agent_id, { mode: body.mode, status: body.status === 'active' ? 'active' : 'paused' });
          }
        }
        toast('AI settings saved', 'ok'); load();
      } catch (err) { toast(err.detail || 'Save failed.', 'danger', 5000); save.disabled = false; }
    } }, 'Save');
    box.append(h('h3', {}, 'AI for this project'),
      h('div', { class: 'field' }, h('label', { for: 'ai-agent' }, 'Agent'), agentSel, choices.length ? null : h('span', { class: 'hint' }, 'No agent exists yet. Create one under Advanced → AI agents.')),
      h('div', { class: 'field' }, h('label', { for: 'ai-mode' }, 'Mode'), modeSel),
      h('div', { class: 'field' }, h('label', { for: 'ai-status' }, 'Status'), statusSel),
      h('div', { class: 'view-actions' }, save), roleNote(ctx, 'admin', 'Changing the AI settings') || '');
    // test
    const text = h('textarea', { class: 'textarea', id: 'ai-test', rows: 3, placeholder: 'Type a customer message, e.g. ' + (row.kind === 'automotive' ? '"Bonjour, prix du filtre à huile ?"' : '"Bonjour, quels sont vos horaires ?"') });
    const out = h('div', {});
    const run = h('button', { class: 'btn btn-secondary', type: 'button', disabled: !manager || undefined, onClick: async () => {
      const t = text.value.trim(); if (!t) return;
      if (!agentSel.value) { toast('Choose an agent first.', 'warn'); return; }
      run.disabled = true; clear(out); out.appendChild(skeletonRows(2));
      try {
        const r = await ctx.api.post('/api/ai/agents/' + agentSel.value + '/test', { project_id: row.id, text: t });
        clear(out);
        const handoff = r.decision === 'handoff';
        out.appendChild(h('div', { class: 'stack xs' },
          h('div', { class: 'chips' }, badge(handoff ? 'Hand to human' : 'Reply', handoff ? 'danger' : 'ok'), r.intent ? chip('Intent: ' + String(r.intent).replace(/_/g, ' ')) : null),
          r.text ? h('div', { class: 'proposed' }, r.text) : h('p', { class: 'dim' }, 'No reply: a human answers this one.')));
      } catch (err) { clear(out); out.appendChild(errorBox(err)); }
      finally { run.disabled = !manager; }
    } }, 'Test');
    box.append(h('h4', {}, 'Test AI'), h('p', { class: 'dim' }, 'Nothing is sent.'), h('div', { class: 'field' }, h('label', { for: 'ai-test', class: 'sr-only' }, 'Customer message'), text), h('div', {}, run), roleNote(ctx, 'manager', 'Testing') || '', out);
  }
  load();
  return root;
}

function catalogueTab(ctx, row) {
  const root = h('div', { class: 'stack' });
  const base = '/api/projects/' + encodeURIComponent(row.id) + '/kitchen';
  const status = h('span', {}, badge('checking', 'mock'));
  ctx.api.get(base + '/describe').then((d) => { clear(status); status.appendChild(badge(d.configured === false ? 'not configured' : (d.reachable === false || d.ok === false ? 'unreachable' : 'connected'), d.configured === false ? 'warn' : (d.reachable === false || d.ok === false) ? 'danger' : 'ok')); }, () => { clear(status); status.appendChild(badge('unavailable', 'warn')); });
  const q = h('input', { class: 'input', type: 'search', placeholder: 'Search parts (reference, title, brand)…', 'aria-label': 'Search products' });
  const list = h('div', {});
  root.appendChild(h('div', { class: 'card' }, h('div', { class: 'card-head' }, h('h3', {}, 'Catalogue (Kitchen Mythos Auto)'), status), h('p', {}, 'Read-only: products, vehicles and prices come from the Kitchen.'), h('div', { class: 'toolbar' }, h('div', { class: 'search' }, q)), list));
  let t = null; q.oninput = () => { clearTimeout(t); t = setTimeout(load, 300); };
  async function load() {
    clear(list); list.appendChild(skeletonRows(4));
    let r; try { r = await ctx.api.get(base + '/products' + ctx.api.qs({ q: q.value.trim(), limit: 50 })); } catch (err) { clear(list); list.appendChild(errorBox(err, load)); return; }
    clear(list);
    const items = r.items || r.products || r.rows || [];
    if (!items.length) { list.appendChild(empty('No product', q.value ? 'Nothing matches.' : 'Type to search the catalogue.')); return; }
    list.appendChild(simpleTable([
      { label: 'Reference', cell: (p) => h('code', {}, p.reference || p.canonical_reference || p.ref || '—') },
      { label: 'Title', cell: (p) => p.title || p.product_title || p.name },
      { label: 'Brand', cell: (p) => p.brand || p.product_brand },
      { label: 'Category', cell: (p) => p.category },
      { label: 'Price', cell: (p) => { const v = p.price_tnd !== undefined && p.price_tnd !== null ? p.price_tnd : p.price; return v !== undefined && v !== null ? String(v) + ' ' + (p.currency || row.currency || '') : null; }, cls: 'num' },
      { label: 'Availability', cell: (p) => p.availability ? badge(p.availability) : null }
    ], items, { onRow: (p) => detail(p.uid || p.product_uid || p.id) }));
    list.appendChild(h('p', { class: 'dim' }, h('small', {}, items.length + ' shown' + (r.total !== undefined ? ' of ' + r.total : ''))));
  }
  async function detail(uid) {
    const d = drawer({ title: 'Product ' + uid, wide: true });
    d.body.appendChild(skeletonRows(4));
    try { const p = await ctx.api.get(base + '/products/' + encodeURIComponent(uid)); clear(d.body); const item = p.item || p.product || p; d.body.append(h('p', { class: 'dim' }, 'Read-only view of the Kitchen record.'), json(item)); }
    catch (err) { clear(d.body); d.body.appendChild(errorBox(err)); }
  }
  load();
  return root;
}

function advancedTab(ctx, row) {
  const settings = Object.assign({}, row.settings || {});
  const root = h('div', { class: 'stack sm' },
    details('Identity and settings', [kv([['Internal id', h('code', {}, row.id)], ['Currency', row.currency], ['Vehicle brand', row.brand_car], ['Kitchen', settings.kitchen ? h('code', {}, settings.kitchen) : null], ['Created', fmtDate(row.created_at)], ['Updated', fmtDate(row.updated_at)]]), h('h4', {}, 'Settings (JSON)'), json(settings)]),
    details('Routing rules', routingPanel(ctx, { project: row.id, fixed: true })),
    details('Automations', automationsPanel(ctx, { project: row.id, fixed: true })),
    details('AI agents', agentsPanel(ctx, { project: row.id })),
    details('AI runs', runsPanel(ctx, { project: row.id, fixed: true })),
    details('Technical integrations', integrationsPanel(ctx, { project: row.id })),
    details('Audit', auditPanel(ctx, { project: row.id, prefKey: 'audit-project' })));
  return root;
}
