'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',textContent:'',style:{display:''}};}
function sandbox(overrides){var ids=['compta-expenses-page','compta-categories-page','category-modal','category-edit-id','category-name','category-icon','category-color','category-subcategories','category-modal-title','expense-category','expense-subcategory','expense-modal','expense-edit-id','expense-date','expense-label','expense-payment','expense-amount','expense-notes'];var els={};ids.forEach(function(id){els[id]=el(id);});var state={expenses:[],categories:[],savedExpenses:0,savedCategories:0,renders:0,alerts:[]};var sb={document:{getElementById:function(id){return els[id]||null;}},STORE:{expenses:function(){return state.expenses;},saveExpenses:function(v){state.expenses=v;state.savedExpenses++;},expenseCategories:function(){return state.categories;},saveExpenseCategories:function(v){state.categories=v;state.savedCategories++;}},_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},todayStr:function(){return'2026-08-04';},isDateInCurrentWeek:function(v){return v==='2026-08-03';},confirm:function(){return true;},alert:function(v){state.alerts.push(v);},renderComptaViews:function(){state.renders++;},fillModalFields:function(prefix,item){els['expense-edit-id'].value=item?item.id:'';},saveModalEntity:function(prefix,getFn,saveFn,fields,renderFn,closeFn){saveFn([{id:'saved'}]);closeFn();renderFn();},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity,parseInt:parseInt};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-expenses.js');['renderExpensesByPaymentType','renderExpensesPage','getDefaultExpenseCategories','getExpenseCategories','renderExpenseCategoryManager','openCategoryModal','closeCategoryModal','saveCategory','editCategory','deleteCategory','initializeExpenseCategories','updateExpenseSubcategories','renderExpenseReportByCategory','setComptaExpenseFilter','openExpenseModal','closeExpenseModal','saveExpense','deleteExpense'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});ok(vm.runInContext('comptaExpenseFilter',s)==='month','expense filter initialized');

console.log('\n2. Categories');var defaults=s.getDefaultExpenseCategories();ok(defaults.length===8,'default categories preserved');ok(defaults[0].name==='Transport','default category names preserved');ok(defaults[0].subcategories.indexOf('Carburant')>=0,'default subcategories preserved');ok(s.getExpenseCategories().length===8,'defaults used when storage empty');s._state.categories=[{id:'custom',name:'Custom',icon:'⭐',color:'#112233',subcategories:['One','Two']}];ok(s.getExpenseCategories().length===1&&s.getExpenseCategories()[0].id==='custom','stored categories preferred');s.renderExpenseCategoryManager();ok(s._els['compta-categories-page'].innerHTML.indexOf('Custom')>=0,'category manager rendered');s.openCategoryModal('custom');ok(s._els['category-name'].value==='Custom','category edit populated');ok(s._els['category-modal'].style.display==='flex','category modal opened');s.closeCategoryModal();ok(s._els['category-modal'].style.display==='none','category modal closed');s._els['category-edit-id'].value='custom';s._els['category-name'].value='Updated';s._els['category-icon'].value='✓';s._els['category-color'].value='#445566';s._els['category-subcategories'].value='Alpha\nBeta';s.saveCategory();ok(s._state.categories[0].name==='Updated','category updated');ok(s._state.categories[0].subcategories.length===2,'subcategories saved');ok(s._state.savedCategories===1,'category update uses STORE write pipeline');s.deleteCategory('custom');ok(s._state.categories.length===0,'category deleted');ok(s._state.savedCategories===2,'category delete uses STORE write pipeline');

console.log('\n3. Category form options');var f=sandbox();load(f,'js/shared/accounting-expenses.js');f._state.categories=[{id:'travel',name:'Travel',icon:'✈️',color:'#123456',subcategories:['Flight','Hotel']}];f.initializeExpenseCategories();ok(f._els['expense-category'].innerHTML.indexOf('Travel')>=0,'expense category options rendered');f._els['expense-category'].value='Travel';f.updateExpenseSubcategories();ok(f._els['expense-subcategory'].innerHTML.indexOf('Flight')>=0,'subcategory options rendered');f._els['expense-category'].value='';f.updateExpenseSubcategories();ok(f._els['expense-subcategory'].innerHTML.indexOf('Sous-catégorie')>=0,'empty subcategory state rendered');

console.log('\n4. Rendering, totals, and filters');var r=sandbox();load(r,'js/shared/accounting-expenses.js');r._state.categories=[{id:'travel',name:'Travel',icon:'✈️',color:'#123456',subcategories:['Flight']}];r.renderExpensesPage();ok(r._els['compta-expenses-page'].innerHTML.indexOf('Aucune dépense')>=0,'empty expenses page rendered');r._state.expenses=[{id:'e1',date:'2026-08-03',label:'Flight <A>',category:'Travel',payment:'Cash',amount:100},{id:'e2',date:'2026-07-01',label:'Old',category:'Travel',payment:'Bank',amount:50}];r.renderExpensesPage();ok(r._els['compta-expenses-page'].innerHTML.indexOf('Flight &lt;A>')>=0,'current-month expense rendered and escaped');ok(r._els['compta-expenses-page'].innerHTML.indexOf('Old')<0,'month filter excludes older expense');var payment=r.renderExpensesByPaymentType(r._state.expenses);ok(payment.indexOf('Cash')>=0&&payment.indexOf('Bank')>=0,'payment report groups methods');ok(payment.indexOf('150.000')>=0,'payment report totals preserved');var category=r.renderExpenseReportByCategory();ok(category.indexOf('Travel')>=0,'category report rendered');ok(category.indexOf('150.000')>=0,'category report total preserved');r.setComptaExpenseFilter('week');ok(r._els['compta-expenses-page'].innerHTML.indexOf('Flight')>=0&&r._els['compta-expenses-page'].innerHTML.indexOf('Old')<0,'week filter applied');r.setComptaExpenseFilter('previous');ok(r._els['compta-expenses-page'].innerHTML.indexOf('Aucune dépense')>=0,'previous-year filter behavior preserved');

console.log('\n5. Expense CRUD');var c=sandbox();load(c,'js/shared/accounting-expenses.js');c._state.categories=[{id:'travel',name:'Travel',icon:'✈️',color:'#123456',subcategories:['Flight']}];c._state.expenses=[{id:'e1',date:'2026-08-01',category:'Travel',subcategory:'Flight'}];c.openExpenseModal('e1');ok(c._els['expense-edit-id'].value==='e1','expense edit populated');ok(c._els['expense-category'].value==='Travel','expense category restored');ok(c._els['expense-subcategory'].innerHTML.indexOf('Flight')>=0,'expense subcategories refreshed');ok(c._els['expense-modal'].style.display==='flex','expense modal opened');c.closeExpenseModal();ok(c._els['expense-modal'].style.display==='none','expense modal closed');c.saveExpense();ok(c._state.expenses[0].id==='saved','save delegates through approved modal helper');ok(c._state.savedExpenses===1,'expense save uses STORE write pipeline');ok(c._state.renders===1,'expense save refreshes accounting views');c._state.expenses=[{id:'delete'}];c.deleteExpense('delete');ok(c._state.expenses.length===0,'expense deleted');ok(c._state.savedExpenses===2,'expense delete uses STORE write pipeline');var guard=sandbox();load(guard,'js/shared/accounting-expenses.js');guard._state.categories=[{id:'x',name:'X',icon:'X',color:'#111111',subcategories:['Y']}];guard.openCategoryModal();guard._els['category-name'].value='';guard._els['category-subcategories'].value='Y';guard.saveCategory();ok(guard._state.alerts.length===1&&guard._state.savedCategories===0,'category name required');

console.log('\n6. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/accounting-expenses.js')>html.indexOf('js/shared/accounting-cash.js'),'expenses script follows accounting dependencies');ok(html.indexOf('js/shared/accounting-expenses.js')<html.indexOf('js/shared/accounting-purchases.js'),'expenses script precedes purchases consumer');['renderExpensesByPaymentType','renderExpensesPage','getExpenseCategories','renderExpenseCategoryManager','renderExpenseReportByCategory','openExpenseModal','saveExpense'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok((app.match(/let comptaExpenseFilter/g)||[]).length===0,'expense filter state removed from app.js');ok(app.indexOf('function renderStatistique(')>=0,'statistics workflow remains in app.js');ok(html.indexOf('js/shared/accounting-reports.js')>html.indexOf('js/shared/accounting-purchases.js'),'reports module follows accounting data modules');

console.log('\nStage 4R: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
