'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function field(value){return{value:value==null?'':String(value),style:{borderColor:'',backgroundColor:''}};}
function sandbox(overrides){var els={'purchase-amount':field('120'),'purchase-tva-total':field(),'purchase-tva':field()};[19,13,7].forEach(function(rate){els['purchase-tva'+rate+'-ht']=field();els['purchase-tva'+rate+'-amount']=field();});var sb={document:{getElementById:function(id){return Object.prototype.hasOwnProperty.call(els,id)?els[id]:null;}},_els:els,num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v).toFixed(3);},console:{log:function(){},warn:function(){},error:function(){}},Number:Number,String:String,Array:Array,Object:Object,Math:Math};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-tva.js');['calculateFromTTC','selectTVARate','updateTVATotal'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});

console.log('\n2. Reverse TVA calculation');s.calculateFromTTC();ok(s._els['purchase-tva-total'].value==='119.000','stamp deducted from TTC total display');ok(s._els['purchase-tva19-ht'].value==='100.000','19 percent HT calculated');ok(s._els['purchase-tva19-amount'].value==='19.000','19 percent TVA calculated');ok(s._els['purchase-tva13-ht'].value===(119/1.13).toFixed(3),'13 percent HT calculated');ok(s._els['purchase-tva13-amount'].value===((119/1.13)*0.13).toFixed(3),'13 percent TVA calculated');ok(s._els['purchase-tva7-ht'].value===(119/1.07).toFixed(3),'7 percent HT calculated');ok(s._els['purchase-tva7-amount'].value===((119/1.07)*0.07).toFixed(3),'7 percent TVA calculated');ok(s._els['purchase-tva'].value===19,'19 percent selected by default');ok(s._els['purchase-tva19-ht'].style.borderColor==='#c9a84c','selected HT highlighted');ok(s._els['purchase-tva13-ht'].style.borderColor==='#333','unselected HT dimmed');ok(s._els['purchase-tva7-amount'].style.backgroundColor==='#0e0e0e','unselected TVA dimmed');

console.log('\n3. Empty, zero, negative, decimal, and missing input');var z=sandbox();load(z,'js/shared/accounting-tva.js');z._els['purchase-amount'].value='';z.calculateFromTTC();ok(z._els['purchase-tva-total'].value==='0.000','empty TTC clamps total to zero');ok(z._els['purchase-tva19-ht'].value==='0.000','empty TTC clamps HT to zero');ok(z._els['purchase-tva19-amount'].value==='0.000','empty TTC clamps TVA to zero');z._els['purchase-amount'].value='0';z.calculateFromTTC();ok(z._els['purchase-tva13-ht'].value==='0.000','zero TTC clamps rate calculations');z._els['purchase-amount'].value='-10';z.calculateFromTTC();ok(z._els['purchase-tva7-amount'].value==='0.000','negative TTC clamps TVA to zero');z._els['purchase-amount'].value='100.555';z.calculateFromTTC();ok(z._els['purchase-tva-total'].value==='99.555','decimal TTC preserves three-decimal formatting');var missing=sandbox();delete missing._els['purchase-amount'];load(missing,'js/shared/accounting-tva.js');ok((function(){try{missing.calculateFromTTC();return true;}catch(e){return false;}})(),'missing TTC field exits safely');ok(missing._els['purchase-tva-total'].value==='','missing TTC leaves result unchanged');

console.log('\n4. Rate selection and DOM contract');var r=sandbox();load(r,'js/shared/accounting-tva.js');r.selectTVARate(13);ok(r._els['purchase-tva'].value===13,'explicit rate stored');ok(r._els['purchase-tva13-ht'].style.borderColor==='#c9a84c','selected 13 percent HT highlighted');ok(r._els['purchase-tva13-amount'].style.backgroundColor==='#1a1a1a','selected 13 percent TVA highlighted');ok(r._els['purchase-tva19-amount'].style.borderColor==='#333','19 percent TVA dimmed');ok(r._els['purchase-tva7-ht'].style.backgroundColor==='#0e0e0e','7 percent HT dimmed');delete r._els['purchase-tva13-ht'];delete r._els['purchase-tva13-amount'];ok((function(){try{r.selectTVARate(13);return true;}catch(e){return false;}})(),'missing rate fields handled safely');

console.log('\n5. Manual TVA total');var t=sandbox();load(t,'js/shared/accounting-tva.js');t._els['purchase-tva19-amount'].value='19.125';t._els['purchase-tva13-amount'].value='13.25';t._els['purchase-tva7-amount'].value='7.5';t.updateTVATotal();ok(t._els['purchase-tva-total'].value==='39.875','supported TVA amounts summed');t._els['purchase-tva19-amount'].value='';t._els['purchase-tva13-amount'].value='0';t._els['purchase-tva7-amount'].value='0.005';t.updateTVATotal();ok(t._els['purchase-tva-total'].value==='0.005','empty, zero, and decimal amounts handled');delete t._els['purchase-tva13-amount'];t.updateTVATotal();ok(t._els['purchase-tva-total'].value==='0.005','missing rate field treated as zero');var noTotal=sandbox();delete noTotal._els['purchase-tva-total'];load(noTotal,'js/shared/accounting-tva.js');ok((function(){try{noTotal.updateTVATotal();return true;}catch(e){return false;}})(),'missing total field exits safely');

console.log('\n6. Integration and exclusions');var index=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),purchases=fs.readFileSync(path.join(BASE,'js/shared/accounting-purchases.js'),'utf8'),reports=fs.readFileSync(path.join(BASE,'js/shared/accounting-reports.js'),'utf8'),overview=fs.readFileSync(path.join(BASE,'js/shared/accounting-overview.js'),'utf8');ok(index.indexOf('js/shared/accounting-tva.js')>index.indexOf('js/shared/accounting-expenses.js'),'TVA script follows existing accounting helpers');ok(index.indexOf('js/shared/accounting-tva.js')<index.indexOf('js/shared/accounting-purchases.js'),'TVA script precedes purchase consumer');['calculateFromTTC','selectTVARate','updateTVATotal'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok(purchases.indexOf('calculateFromTTC()')>=0,'purchase form retains calculator call');ok(index.indexOf('onchange="updateTVATotal()"')>=0,'inline TVA total handler preserved');ok(index.indexOf('id="purchase-tva" value="19"')>=0,'purchase rate DOM contract preserved');ok(reports.indexOf('function calculateFromTTC(')<0,'reports do not duplicate purchase TVA calculator');ok(overview.indexOf('function calculateFromTTC(')<0,'overview does not duplicate purchase TVA calculator');ok(app.indexOf('function fillModalFields(')<0,'generic modal helper extracted from app.js');ok(app.indexOf('function renderStatistique(')<0,'statistics dashboard extracted from app.js');

console.log('\nStage 4W: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
