'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function sandbox(overrides){var state={invoices:[],purchases:[],expenses:[],bank:[],cash:[],suppliers:[]},els={'compta-dashboard':{innerHTML:''}},calls={flow:0};var sb={document:{getElementById:function(id){return els[id]||null;}},STORE:{invoices:function(){return state.invoices;},purchases:function(){return state.purchases;},expenses:function(){return state.expenses;},bankEntries:function(){return state.bank;},cashEntries:function(){return state.cash;},suppliers:function(){return state.suppliers;}},_state:state,_els:els,_calls:calls,todayStr:function(){return'2026-08-04';},isDateInCurrentWeek:function(v){return v==='2026-08-03'||v==='2026-08-04';},getInvoiceTotal:function(i){return Number(i.total||0);},getExpenseCategories:function(){return{Travel:{},Other:{}};},renderFinancialFlowDiagram:function(){calls.flow++;return'<div id="flow">FLOW</div>';},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals and initial state');var s=sandbox();load(s,'js/shared/accounting-overview.js');ok(typeof s.filterByPeriod==='function','filterByPeriod is global');ok(typeof s.renderComptaViews==='function','renderComptaViews is global');ok(vm.runInContext('comptaDashboardPeriod',s)==='all','overview period initialized to all');

console.log('\n2. Period filtering');var items=[{id:'today',date:'2026-08-04'},{id:'week',date:'2026-08-03'},{id:'month',date:'2026-08-01'},{id:'year',date:'2026-01-01'},{id:'old',date:'2025-12-31'}];ok(s.filterByPeriod(items).length===5,'all period returns all items');ok(s.filterByPeriod(items,'date','day').length===1,'day boundary applied');ok(s.filterByPeriod(items,'date','week').length===2,'week helper applied');ok(s.filterByPeriod(items,'date','month').length===3,'month prefix applied');ok(s.filterByPeriod(items,'date','year').length===4,'year prefix applied');ok(s.filterByPeriod(items,'date','unknown').length===5,'unknown period preserves items');var custom=[{created:'2026-08-04'},{created:'2025-08-04'}];ok(s.filterByPeriod(custom,'created','year').length===1,'custom date field supported');

console.log('\n3. Overview calculations and cards');s._state.invoices=[{date:'2026-08-04',total:200},{date:'2025-01-01',total:800}];s._state.purchases=[{date:'2026-08-04',amount:50},{date:'2025-01-01',amount:500}];s._state.expenses=[{date:'2026-08-04',amount:25},{date:'2025-01-01',amount:250}];s._state.bank=[{date:'2026-07-01',balance:300},{date:'2026-08-01',balance:400}];s._state.cash=[{id:'c1'}];s._state.suppliers=[{id:'s1'},{id:'s2'}];s.renderComptaViews();var html=s._els['compta-dashboard'].innerHTML;ok(html.indexOf('Résumé financier - Tout')>=0,'all-period heading rendered');ok(html.indexOf('1000.000')>=0,'all-period income rendered');ok(html.indexOf('550.000')>=0,'all-period purchases rendered');ok(html.indexOf('275.000')>=0,'all-period expenses rendered');ok(html.indexOf('+175.000')>=0,'all-period net result rendered');ok(html.indexOf('400.000')>=0,'latest bank balance rendered');ok(html.indexOf('2 fournisseurs')>=0,'supplier summary rendered');ok(html.indexOf('1 entrées')>=0,'cash summary rendered');ok(html.indexOf('2 catégories')>=0,'expense categories composed');ok(html.indexOf('id="flow"')>=0,'financial flow report composed');ok(s._calls.flow===1,'financial flow rendered once');

console.log('\n4. Period state and filtered cards');vm.runInContext("comptaDashboardPeriod='day'",s);s.renderComptaViews();html=s._els['compta-dashboard'].innerHTML;ok(html.indexOf('Résumé financier - Jour')>=0,'day period label rendered');ok(html.indexOf('200.000')>=0,'day income filtered');ok(html.indexOf('50.000')>=0,'day purchases filtered');ok(html.indexOf('25.000')>=0,'day expenses filtered');ok(html.indexOf('+125.000')>=0,'day net result calculated');ok(html.indexOf("comptaDashboardPeriod='month'; renderComptaViews()")>=0,'period navigation contract preserved');ok(s._calls.flow===2,'flow composed once per overview render');var missing=sandbox();missing.document.getElementById=function(){return null;};load(missing,'js/shared/accounting-overview.js');missing.renderComptaViews();ok(missing._calls.flow===0,'missing dashboard exits before composition');

console.log('\n5. Navigation and composition');ok(html.indexOf("showView('compta-suppliers')")>=0,'supplier navigation preserved');ok(html.indexOf("showView('compta-purchases')")>=0,'purchase navigation preserved');ok(html.indexOf("showView('compta-expenses')")>=0,'expense navigation preserved');ok(html.indexOf("showView('compta-bank')")>=0,'bank navigation preserved');ok(html.indexOf("showView('compta-cash')")>=0,'cash navigation preserved');ok(html.indexOf("showView('compta-reconciliation')")>=0,'reconciliation navigation preserved');ok(html.indexOf('Connexions comptables')>=0,'accounting connections rendered');

console.log('\n6. Integration');var index=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),router=fs.readFileSync(path.join(BASE,'js/core/router.js'),'utf8');ok(index.indexOf('js/shared/accounting-overview.js')>index.indexOf('js/shared/accounting-reports.js'),'overview script follows reports dependency');ok(index.indexOf('js/shared/accounting-overview.js')<index.indexOf('js/taches.js'),'overview script precedes consumers');ok(app.indexOf('function filterByPeriod(')<0,'filterByPeriod removed from app.js');ok(app.indexOf('function renderComptaViews(')<0,'renderComptaViews removed from app.js');ok((app.match(/let comptaDashboardPeriod/g)||[]).length===0,'overview state removed from app.js');ok(router.indexOf("if (view === 'comptabilite') renderComptaViews()")>=0,'router compatibility call preserved');ok(app.indexOf('function renderSuppliersPage(')<0,'supplier management extracted from app.js');ok(app.indexOf('function calculateFromTTC(')<0,'TVA calculation extracted from app.js');ok(app.indexOf('function renderStatistique(')>=0,'unrelated statistics remain in app.js');

console.log('\nStage 4U: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
