'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path');
var BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',style:{display:''},dataset:{},options:[{value:'pending',dataset:{fee:'0'}}],selectedIndex:0};}
function sandbox(overrides){
 var ids=['rdv-date-picker','rdv-time-picker','rdv-modal-step1','rdv-modal-step2','rdv-existing','rdv-client','rdv-collab','rdv-nature','rdv-rep','rdv-fee-invoice','rdv-fee-devis','rdv-fee-contract','rdv-fee-type-select','rdv-direct-section','rdv-invoice-section','rdv-devis-section','rdv-contract-section','rdv-fee-amount','rdv-fee-invoice-amount','rdv-fee-devis-amount','rdv-fee-contract-amount','rdv-lieu','rdv-notes','rdv-status','rdv-list'];
 var els={};ids.forEach(function(id){els[id]=el(id);});
 var state={rdvs:[],invoices:[],devis:[],contracts:[],clients:[],collabs:[],natures:[],reps:[],alerts:[],deleted:[]};
 var sb={document:{getElementById:function(id){return els[id]||null;}},STORE:{
  rdvs:function(){return state.rdvs;},saveRdvs:function(v){state.rdvs=v;},invoices:function(){return state.invoices;},devis:function(){return state.devis;},contracts:function(){return state.contracts;},clients:function(){return state.clients;},collabs:function(){return state.collabs;},natures:function(){return state.natures;},representations:function(){return state.reps;}
 },_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},todayStr:function(){return'2026-08-02';},alert:function(v){state.alerts.push(v);},confirm:function(){return true;},_markDeleted:function(k,id){state.deleted.push([k,id]);},setTimeout:function(fn){fn();},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Array:Array,Object:Object,String:String,Number:Number,Math:Math,parseFloat:parseFloat};
 Object.assign(sb,overrides||{});return vm.createContext(sb);
}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}
console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/rdvs.js');
['rdvOpenForm','rdvClose','rdvShowExistingRdvs','rdvGoToStep2','rdvBackToStep1','getAllInvoices','getAllDevis','getAllContracts','rdvLoadDropdowns','rdvCalcFee','rdvFeeTypeSelectChanged','rdvInvoiceChanged','rdvDevisChanged','rdvContractChanged','rdvSave','rdvRender','rdvEdit','rdvDelete'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});

console.log('\n2. Wizard and daily list');s.rdvOpenForm();ok(s._els['rdv-date-picker'].value==='2026-08-02','open initializes date');ok(s._els['rdv-time-picker'].value==='09:00','open initializes time');ok(s._els['rdv-modal-step1'].style.display==='flex','step one opened');ok(s._els['rdv-modal-step1'].dataset.editId==='','new edit id cleared');
s.rdvClose();ok(s._els['rdv-modal-step1'].style.display==='none'&&s._els['rdv-modal-step2'].style.display==='none','wizard closed');
s._els['rdv-date-picker'].value='2026-08-02';s._state.rdvs=[];s.rdvShowExistingRdvs();ok(s._els['rdv-existing'].innerHTML.indexOf('Pas de rendez-vous')>=0,'empty daily list');
s._state.rdvs=[{date:'2026-08-02',time:'10:00',client:'A < B',fee:20}];s.rdvShowExistingRdvs();ok(s._els['rdv-existing'].innerHTML.indexOf('A &lt; B')>=0,'daily client escaped');ok(s._els['rdv-existing'].innerHTML.indexOf('20.000')>=0,'daily fee rendered');
s._els['rdv-date-picker'].value='';s.rdvGoToStep2();ok(s._state.alerts.length===1,'date required');s._els['rdv-date-picker'].value='2026-08-03';s._els['rdv-time-picker'].value='11:00';s.rdvGoToStep2();ok(s._els['rdv-modal-step1'].dataset.selectedDate==='2026-08-03','selected date retained');ok(s._els['rdv-modal-step2'].style.display==='flex','step two opened');s.rdvBackToStep1();ok(s._els['rdv-modal-step1'].style.display==='flex','back returns to step one');

console.log('\n3. Sources and dropdowns');s._state.invoices=[{id:'i1',num:'1',ttc:100},{id:'bad',ref:'CONT-1'}];s._state.devis=[{id:'d1',num:'D',totalTTC:200},{id:'bad',ref:'CONT-2'}];s._state.contracts=[{id:'c1',ref:'CONT-3',amount:300},{id:'bad',ref:'X'}];
ok(s.getAllInvoices().length===1,'contracts excluded from invoices');ok(s.getAllDevis().length===1,'contracts excluded from devis');ok(s.getAllContracts().length===1,'only contract references returned');
s._state.clients=[{name:'Client'}];s._state.collabs=[{nom:'Collab'}];s._state.natures=[{nom:'Nature'}];s._state.reps=[{id:'r1',spectacle:'Show',fee:40}];s._els['rdv-fee-type-select'].value='direct';s.rdvLoadDropdowns();ok(s._els['rdv-client'].innerHTML.indexOf('Client')>=0,'clients loaded');ok(s._els['rdv-collab'].innerHTML.indexOf('Collab')>=0,'collaborators loaded');ok(s._els['rdv-nature'].innerHTML.indexOf('Nature')>=0,'natures loaded');ok(s._els['rdv-fee-invoice'].innerHTML.indexOf('100.000')>=0,'invoice source loaded');ok(s._els['rdv-fee-contract'].innerHTML.indexOf('300.000')>=0,'contract source loaded');

console.log('\n4. Fee workflow');['direct','invoice','devis','contract'].forEach(function(type){s._els['rdv-fee-type-select'].value=type;s.rdvFeeTypeSelectChanged();ok(s._els['rdv-'+type+'-section'].style.display==='block',type+' section shown');});
s._els['rdv-fee-type-select'].value='direct';s._els['rdv-rep'].options=[{dataset:{fee:'42'}}];s._els['rdv-rep'].selectedIndex=0;s.rdvCalcFee();ok(s._els['rdv-fee-amount'].value==='42.000','representation fee calculated');
s._els['rdv-fee-invoice'].value='i1';s.rdvInvoiceChanged();ok(s._els['rdv-fee-invoice-amount'].value==='100.000','invoice amount selected');s._els['rdv-fee-devis'].value='d1';s.rdvDevisChanged();ok(s._els['rdv-fee-devis-amount'].value==='200.000','devis amount selected');s._els['rdv-fee-contract'].value='c1';s.rdvContractChanged();ok(s._els['rdv-fee-contract-amount'].value==='300.000','contract amount selected');

function form(x,id){x._els['rdv-modal-step1'].dataset.selectedDate='2026-08-04';x._els['rdv-modal-step1'].dataset.selectedTime='12:00';x._els['rdv-modal-step1'].dataset.editId=id||'';x._els['rdv-fee-type-select'].value='direct';x._els['rdv-fee-amount'].value='55';x._els['rdv-client'].value='Client';x._els['rdv-collab'].value='Collab';x._els['rdv-rep'].value='r1';x._els['rdv-nature'].value='Nature';x._els['rdv-lieu'].value='Tunis';x._els['rdv-notes'].value='Note';x._els['rdv-status'].value='planned';}
console.log('\n5. CRUD');var c=sandbox();load(c,'js/shared/rdvs.js');form(c);c.rdvSave();ok(c._state.rdvs.length===1,'RDV created');ok(c._state.rdvs[0].fee===55,'direct fee saved');ok(c._state.rdvs[0].feeData.type==='direct','fee metadata saved');ok(c._els['rdv-modal-step2'].style.display==='none','save closes wizard');ok(c._els['rdv-list'].innerHTML.indexOf('Client')>=0,'save rerenders list');
var id=c._state.rdvs[0].id;form(c,id);c._els['rdv-lieu'].value='Sfax';c.rdvSave();ok(c._state.rdvs.length===1&&c._state.rdvs[0].lieu==='Sfax','RDV updated');c.rdvEdit(id);ok(c._els['rdv-modal-step1'].dataset.editId===id,'edit id populated');ok(c._els['rdv-client'].value==='Client','edit client populated');ok(c._els['rdv-fee-amount'].value==='55.000','edit fee populated');ok(c._els['rdv-modal-step2'].style.display==='flex','edit opens step two');
c.rdvDelete(id);ok(c._state.rdvs.length===0,'RDV deleted');ok(c._state.deleted.length===1&&c._state.deleted[0][0]==='mp_rdvs','tombstone recorded');
var cancelled=sandbox({confirm:function(){return false;}});load(cancelled,'js/shared/rdvs.js');cancelled._state.rdvs=[{id:'keep'}];cancelled.rdvDelete('keep');ok(cancelled._state.rdvs.length===1,'cancelled delete preserves RDV');
var empty=sandbox();load(empty,'js/shared/rdvs.js');empty.rdvRender();ok(empty._els['rdv-list'].innerHTML.indexOf('Aucun rendez-vous')>=0,'empty RDV list rendered');

console.log('\n6. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/rdvs.js')>html.indexOf('js/shared/invoices.js'),'RDV script follows dependencies');ok(html.indexOf('js/shared/rdvs.js')<html.indexOf('js/taches.js'),'RDV script precedes downstream tasks');ok((app.match(/function rdvOpenForm\(/g)||[]).length===0,'rdvOpenForm removed from app.js');ok((app.match(/function rdvSave\(/g)||[]).length===0,'rdvSave removed from app.js');ok((app.match(/function rdvRender\(/g)||[]).length===0,'rdvRender removed from app.js');ok((app.match(/function removePersonRow\(/g)||[]).length===1,'following compatibility helper preserved');
console.log('\nStage 4N: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
