'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function sandbox(overrides){var state={invoices:[],rdvs:[],purchases:[],expenses:[],bank:[],cash:[]},els={'compta-reconciliation-page':{innerHTML:''}};var sb={document:{getElementById:function(id){return els[id]||null;}},STORE:{invoices:function(){return state.invoices;},rdvs:function(){return state.rdvs;},purchases:function(){return state.purchases;},expenses:function(){return state.expenses;},bankEntries:function(){return state.bank;},cashEntries:function(){return state.cash;}},_state:state,_els:els,todayStr:function(){return'2026-08-04';},normalizeRdv:function(r){return r;},getInvoiceTotal:function(i){return Number(i.total||0);},getRdvAmount:function(r){return Number(r.amount||0);},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity,parseInt:parseInt};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}
function seed(s){s._state.invoices=[{id:'i1',date:'2026-01-15',total:100,linked:true},{id:'i2',date:'2025-12-01',total:900}];s._state.rdvs=[{id:'r1',date:'2026-01-20',amount:50}];s._state.purchases=[{id:'p1',date:'2026-01-05',amount:30}];s._state.expenses=[{id:'e1',date:'2026-01-06',amount:20}];s._state.bank=[{id:'b1',date:'2026-08-01',balance:400,linkedId:'i1',linkedType:'invoice'},{id:'b2',date:'2026-07-01',balance:350,linkedId:'e1',linkedType:'expense'}];s._state.cash=[{id:'c1',date:'2026-08-01',amount:25}];}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-reports.js');['generateMonthlyReport','renderFinancialFlowDiagram','renderReconciliationPage','renderFinancialAnalyticsDashboard'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});

console.log('\n2. Monthly report calculations');seed(s);var report=s.generateMonthlyReport();ok(report.year==='2026','current year selected');ok(report.totals.income===150,'invoice and RDV income totaled');ok(report.totals.purchases===30,'purchase total calculated');ok(report.totals.expenses===20,'expense total calculated');ok(report.totals.netProfit===100,'net profit formula preserved');ok(report.counts.invoices===1,'year filters invoices');ok(report.counts.rdvs===1,'year filters RDVs');ok(report.counts.purchases===1,'year filters purchases');ok(report.counts.expenses===1,'year filters expenses');ok(report.monthly['01'].sales===100,'monthly invoice total calculated');ok(report.monthly['01'].calendar===50,'monthly RDV total calculated');ok(report.monthly['01'].purchases===30,'monthly purchase total calculated');ok(report.monthly['01'].expenses===20,'monthly expense total calculated');ok(report.monthly['02'].sales===0,'empty month initialized');var prior=s.generateMonthlyReport('2025');ok(prior.year==='2025'&&prior.totals.income===900,'explicit year filter preserved');

console.log('\n3. Financial flow diagram');var flow=s.renderFinancialFlowDiagram();ok(flow.indexOf('Flux de trésorerie')>=0,'flow diagram rendered');ok(flow.indexOf('1050.000')>=0,'flow income rendered across all years');ok(flow.indexOf('30.000')>=0,'flow purchases rendered');ok(flow.indexOf('20.000')>=0,'flow expenses rendered');ok(flow.indexOf('+1000.000')>=0,'positive result rendered');ok(flow.indexOf('400.000')>=0,'latest bank balance rendered');ok(flow.indexOf('2 mouvements')>=0,'bank movement count rendered');var loss=sandbox();load(loss,'js/shared/accounting-reports.js');loss._state.expenses=[{amount:10}];ok(loss.renderFinancialFlowDiagram().indexOf('-10.000')>=0,'negative result preserved');

console.log('\n4. Reconciliation');var rec=s.renderReconciliationPage();ok(typeof rec==='string','reconciliation returns markup');ok(rec.indexOf('Réconciliation Comptable Complète')>=0,'reconciliation heading rendered');ok(rec.indexOf('1050.000')>=0,'reconciliation income rendered across all years');ok(rec.indexOf('50.000')>=0,'reconciliation costs rendered');ok(rec.indexOf('+1000.000')>=0,'reconciliation net result rendered');ok(rec.indexOf('400.000')>=0,'reconciliation bank balance rendered');ok(rec.indexOf('25.000')>=0,'reconciliation cash total rendered');ok(rec.indexOf('1/3')>=0,'linked income count preserved');ok(rec.indexOf('1/1')>=0,'linked expense count preserved');ok(rec.indexOf('Liquidité Totale')>=0,'liquidity verification rendered');ok(s._els['compta-reconciliation-page'].innerHTML==='','existing return-before-DOM behavior preserved');var empty=sandbox();load(empty,'js/shared/accounting-reports.js');ok(empty.renderReconciliationPage().indexOf('NaN%')>=0,'empty reconciliation percentage behavior preserved');

console.log('\n5. Analytics dashboard');var analytics=s.renderFinancialAnalyticsDashboard();ok(analytics.indexOf('Analyse financière annuelle 2026')>=0,'analytics year rendered');ok(analytics.indexOf("Chiffre d'affaires")>=0,'income card rendered');ok(analytics.indexOf('100.000')>=0,'net result rendered');ok(analytics.indexOf('Synthèse mensuelle')>=0,'monthly summary rendered');ok(analytics.indexOf('JAN')>=0&&analytics.indexOf('DEC')>=0,'all month labels rendered');ok(analytics.indexOf('width:100%')>=0,'monthly income proportion preserved');var blank=sandbox();load(blank,'js/shared/accounting-reports.js');ok(blank.renderFinancialAnalyticsDashboard().indexOf('0.000')>=0,'empty analytics totals rendered');

console.log('\n6. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),router=fs.readFileSync(path.join(BASE,'js/core/router.js'),'utf8');ok(html.indexOf('js/shared/accounting-reports.js')>html.indexOf('js/shared/accounting-purchases.js'),'reports script follows accounting data modules');ok(html.indexOf('js/shared/accounting-reports.js')<html.indexOf('js/shared/accounting-overview.js'),'reports script precedes overview consumer');['generateMonthlyReport','renderFinancialFlowDiagram','renderReconciliationPage','renderFinancialAnalyticsDashboard'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok(router.indexOf('renderReconciliationPage()')>=0,'router compatibility call preserved');ok(html.indexOf('js/shared/accounting-overview.js')>html.indexOf('js/shared/accounting-reports.js'),'overview module owns report composition');ok(app.indexOf('function renderSuppliersPage(')<0,'supplier management extracted from app.js');ok(app.indexOf('function calculateFromTTC(')<0,'TVA calculation extracted from app.js');ok(app.indexOf('function renderStatistique(')>=0,'unrelated statistics remain in app.js');

console.log('\nStage 4T: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
