'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',style:{display:''}};}
function sandbox(overrides){var ids=['compta-suppliers-page','supplier-modal','supplier-edit-id','supplier-name','supplier-contact','supplier-addr','supplier-mf','supplier-rib','supplier-category','supplier-search','supplier-filter-category'],els={};ids.forEach(function(id){els[id]=el(id);});var state={suppliers:[],purchases:[],bank:[],saved:0,purchaseOptions:0,modalSaves:0};var sb={document:{getElementById:function(id){return els[id]||null;}},STORE:{suppliers:function(){return state.suppliers;},saveSuppliers:function(v){state.suppliers=v;state.saved++;},purchases:function(){return state.purchases;},bankEntries:function(){return state.bank;}},_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},fillModalFields:function(prefix,item){els['supplier-edit-id'].value=item?item.id:'';els['supplier-name'].value=item?item.name||'':'';},saveModalEntity:function(prefix,getFn,saveFn,fields,renderFn,closeFn){state.modalSaves++;saveFn([{id:'saved',name:'Saved'}]);closeFn();renderFn();},fillPurchaseSuppliers:function(){state.purchaseOptions++;},openPurchaseModal:function(){},deletePurchase:function(){},openBankDetailModal:function(){},confirm:function(){return true;},console:{log:function(){},warn:function(){},error:function(){}},Number:Number,String:String,Array:Array,Object:Object,Set:Set,Math:Math};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals and state');var s=sandbox();load(s,'js/shared/accounting-suppliers.js');['renderSuppliersPage','showSupplierDetail','getSupplierCategoryStyle','setSupplierSearch','setSupplierFilterCategory','resetSupplierFilters','openSupplierModal','closeSupplierModal','saveSupplier','deleteSupplier'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});ok(vm.runInContext('supplierFilterCategory',s)==='all','category filter initialized');ok(vm.runInContext('supplierSearchQuery',s)==='','search initialized');

console.log('\n2. List rendering and filters');s._state.suppliers=[{id:'s2',name:'Zulu',contact:'222',addr:'South',category:'Services'},{id:'s1',name:'Alpha <One>',contact:'111',addr:'North',category:'Matériel'}];s.renderSuppliersPage();var html=s._els['compta-suppliers-page'].innerHTML;ok(html.indexOf('Alpha &lt;One>')>=0,'supplier name escaped');ok(html.indexOf('Alpha &lt;One>')<html.indexOf('Zulu'),'suppliers sorted by name');ok(html.indexOf('2 fournisseur(s)')>=0,'visible count rendered');ok(html.indexOf('showSupplierDetail')>=0,'detail navigation rendered');ok(html.indexOf('openSupplierModal')>=0,'edit action rendered');s.setSupplierSearch('zulu');ok(s._els['compta-suppliers-page'].innerHTML.indexOf('1 fournisseur(s)')>=0,'search filter applied');s.setSupplierFilterCategory('Matériel');ok(s._els['compta-suppliers-page'].innerHTML.indexOf('Aucun fournisseur.')<0,'combined filter preserves legacy non-empty result flow');s.resetSupplierFilters();ok(s._els['supplier-search'].value===''&&s._els['supplier-filter-category'].value==='all','filter controls reset');ok(s._els['compta-suppliers-page'].innerHTML.indexOf('2 fournisseur(s)')>=0,'reset rerenders all suppliers');var empty=sandbox();load(empty,'js/shared/accounting-suppliers.js');empty.renderSuppliersPage();ok(empty._els['compta-suppliers-page'].innerHTML.indexOf('Aucun fournisseur')>=0,'empty state rendered');

console.log('\n3. Detail, purchase, and bank links');var d=sandbox();load(d,'js/shared/accounting-suppliers.js');d._state.suppliers=[{id:'s1',name:'Supplier',contact:'123',category:'Services'}];d._state.purchases=[{id:'p1',supplierName:'Supplier',num:'ACH-001',date:'2026-08-01',amount:100,notes:'Order'}];d._state.bank=[{id:'b1',linkedId:'s1',linkedType:'supplier',date:'2026-08-02',type:'Transfer',label:'Paid',direction:'Debit',amount:75},{id:'b2',linkedId:'s1',linkedType:'client',amount:999}];d.showSupplierDetail('s1');html=d._els['compta-suppliers-page'].innerHTML;ok(html.indexOf('ACH-001')>=0,'linked purchase rendered');ok(html.indexOf("openPurchaseModal('p1')")>=0,'purchase navigation preserved');ok(html.indexOf("deletePurchase('p1')")>=0,'purchase deletion link preserved');ok(html.indexOf("openBankDetailModal('b1')")>=0,'bank navigation preserved');ok(html.indexOf('100.000')>=0,'purchase total formatted');ok(html.indexOf('75.000')>=0,'bank total formatted');ok(html.indexOf('999.000')<0,'unrelated bank entry excluded');var before=html;d.showSupplierDetail('missing');ok(d._els['compta-suppliers-page'].innerHTML===before,'missing supplier leaves page unchanged');

console.log('\n4. Category styling');ok(s.getSupplierCategoryStyle('Services').icon==='💼','known category style preserved');ok(s.getSupplierCategoryStyle('Unknown').icon==='📦','fallback category style preserved');

console.log('\n5. CRUD and write pipeline');var c=sandbox();load(c,'js/shared/accounting-suppliers.js');c._state.suppliers=[{id:'s1',name:'Existing'}];c.openSupplierModal('s1');ok(c._els['supplier-edit-id'].value==='s1','existing supplier loaded');ok(c._els['supplier-modal'].style.display==='flex','supplier modal opened');c.closeSupplierModal();ok(c._els['supplier-modal'].style.display==='none','supplier modal closed');c.saveSupplier();ok(c._state.modalSaves===1,'save delegates to approved modal helper');ok(c._state.saved===1,'save uses STORE write pipeline');ok(c._state.purchaseOptions===1,'purchase supplier options synchronized');c._state.suppliers=[{id:'delete'},{id:'keep'}];c.deleteSupplier('delete');ok(c._state.suppliers.length===1&&c._state.suppliers[0].id==='keep','supplier deleted');ok(c._state.saved===2,'delete uses STORE write pipeline');

console.log('\n6. Integration');var index=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),router=fs.readFileSync(path.join(BASE,'js/core/router.js'),'utf8');ok(index.indexOf('js/shared/accounting-suppliers.js')>index.indexOf('js/shared/accounting-purchases.js'),'supplier script follows purchase dependency');ok(index.indexOf('js/shared/accounting-suppliers.js')>index.indexOf('js/shared/accounting-bank.js'),'supplier script follows bank dependency');ok(index.indexOf('js/shared/accounting-suppliers.js')<index.indexOf('js/shared/accounting-reports.js'),'supplier script precedes accounting consumers');['renderSuppliersPage','showSupplierDetail','getSupplierCategoryStyle','setSupplierSearch','setSupplierFilterCategory','resetSupplierFilters','openSupplierModal','closeSupplierModal','saveSupplier','deleteSupplier'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok((app.match(/let supplierFilterCategory/g)||[]).length===0,'supplier filter state removed from app.js');ok((app.match(/let supplierSearchQuery/g)||[]).length===0,'supplier search state removed from app.js');ok(router.indexOf("if (view === 'compta-suppliers') renderSuppliersPage()")>=0,'router compatibility call preserved');ok(app.indexOf('function renderEntityPage(')>=0,'generic entity helper remains in app.js');ok(app.indexOf('function calculateFromTTC(')<0,'TVA calculation extracted from app.js');ok(app.indexOf('function renderStatistique(')<0,'statistics dashboard extracted from app.js');ok(index.indexOf('js/shared/fournisseurs.js')>=0,'legacy fournisseurs module remains distinct');

console.log('\nStage 4V: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
