'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',textContent:'',checked:false,src:'',style:{display:''},children:[],appendChild:function(c){this.children.push(c);},remove:function(){this.removed=true;},querySelectorAll:function(){return[];}};}
function row(desc,qty,pu,unit){var map={'.dev-line-desc':{value:desc},'.dev-line-qty':{value:String(qty)},'.dev-line-pu':{value:String(pu)},'.dev-line-unit':{value:unit||'Forfait'},'.dev-line-total':{textContent:''}};return{map:map,querySelector:function(s){return map[s]||null;},remove:function(){this.removed=true;}};}
function sandbox(overrides){var ids=['dev-edit-id','dev-date','dev-client-name','dev-client-addr','dev-client-mf','dev-addStamp','dev-tva-percent','dev-timbre-amount','dev-societe','dev-logo-override','dev-logo-custom','dev-lines-body','dev-num-year','dev-num-seq','dev-num','dev-num-preview','devis-container','dev-logo-preview','devis-form-title','dev-client-select','dev-total-ht','dev-total-ttc','dev-tva','dev-t-ht','dev-t-tva','dev-t-timbre','dev-t-ttc','devis-preview','devis-preview-modal'];var els={};ids.forEach(function(id){els[id]=el(id);});var rows=[],state={devis:[],clients:[],views:[],alerts:[],logs:[]};els['dev-lines-body'].querySelectorAll=function(s){return s==='tr'?rows:[];};var sb={
 MYTHOS_PRINT_LOGO_SRC:'mythos.png',
 document:{getElementById:function(id){return els[id]||null;},createElement:function(){var r=row('',0,0);rows.push(r);return r;}},STORE:{devis:function(){return state.devis;},saveDevis:function(v){state.devis=v;},clients:function(){return state.clients;}},LOGGER:{log:function(a,d){state.logs.push([a,d]);}},_els:els,_rows:rows,_state:state,
 esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},escapeHtml:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},fmtMoney:function(v){return Number(v||0).toFixed(3);},num:function(v){return Number(v||0);},formatDate:function(v){return String(v||'');},numberToFrenchWords:function(v){return'WORDS:'+v;},todayStr:function(){return'2026-08-02';},showView:function(v){state.views.push(v);},alert:function(v){state.alerts.push(v);},confirm:function(){return true;},setTimeout:function(fn){fn();},btoa:function(v){return'B64:'+v;},unescape:unescape,encodeURIComponent:encodeURIComponent,FileReader:function(){this.readAsDataURL=function(){this.onload({target:{result:'data:image/x'}});};},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Array:Array,Object:Object,String:String,Number:Number,Math:Math,parseFloat:parseFloat,parseInt:parseInt,Infinity:Infinity};Object.assign(sb,overrides||{});var __ctx=vm.createContext(sb);vm.runInContext(fs.readFileSync(path.join(BASE,'js/shared/financial-calc.js'),'utf8'),__ctx);return __ctx;}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}
console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/devis.js');['getStampSVGFor','nextDevisNum','splitDevisNum','editDevis','deleteDevis','saveDevis','populateDevisList','cancelDevisForm','updateDevisLogoPreview','onDevisSocieteChange','onDevisLogoFileChange','resetDevisLogo','syncDevisNumberPreview','initDevisForm','fillDevisClientSelect','syncDevisClientFromSelect','addDevisLine','removeDevisLine','calcDevisTotals','buildDevisHTML','printDevis','closeDevisPreview'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});ok(vm.runInContext('devisLineCount',s)===0,'line counter initialized');
console.log('\n2. Numbering and stamp');ok(s.nextDevisNum(2026)==='001/2026','first number');s._state.devis=[{num:'002/2026'},{num:'DEV-2026/009'},{num:'100/2025'}];ok(s.nextDevisNum(2026)==='003/2026','existing numbering filter behavior preserved');var p=s.splitDevisNum('007/2026');ok(p.seq==='007'&&p.year==='2026','modern number split');p=s.splitDevisNum('DEV-2025/12');ok(p.seq==='12'&&p.year==='2025','legacy number split');ok(s.splitDevisNum('bad').seq==='','invalid number handled');ok(s.getStampSVGFor('mythos').indexOf('data:image/svg+xml;base64,')===0,'stamp data URL generated');
console.log('\n3. List and form');s._state.devis=[];s.populateDevisList();ok(s._els['devis-container'].innerHTML.indexOf('Aucun devis')>=0,'empty list rendered');s._state.devis=[{id:'d1',num:'001/2026',clientName:'A < B',date:'2026-08-02',totalHT:100,tvaPercent:7,totalTTC:108}];s.populateDevisList();ok(s._els['devis-container'].innerHTML.indexOf('A &lt; B')>=0,'client escaped');ok(s._els['devis-container'].innerHTML.indexOf('001/2026')>=0,'number rendered');s._els['dev-num-year'].value='2026';s._els['dev-num-seq'].value='7';s.syncDevisNumberPreview();ok(s._els['dev-num'].value==='007/2026','internal number normalized');ok(s._els['dev-num-preview'].textContent==='DEV-2026/7','display number formatted');s._state.clients=[{id:'c1',name:'Client <One>',addr:'Addr',mf:'MF'}];s.fillDevisClientSelect();ok(s._els['dev-client-select'].innerHTML.indexOf('Client &lt;One>')>=0,'client options escaped');s._els['dev-client-select'].value='c1';s.syncDevisClientFromSelect();ok(s._els['dev-client-name'].value==='Client <One>','client synchronized');ok(s._els['dev-client-mf'].value==='MF','client tax id synchronized');
s._els['dev-societe'].value='kacem';s.updateDevisLogoPreview();ok(s._els['dev-logo-preview'].src==='assets/logos/logo-kacem.png','issuer logo selected');s._els['dev-logo-override'].value='custom.png';s.updateDevisLogoPreview();ok(s._els['dev-logo-preview'].src==='custom.png','custom logo selected');s.onDevisSocieteChange();ok(s._els['dev-logo-override'].value==='','issuer change resets override');s._els['dev-logo-override'].value='x';s.resetDevisLogo();ok(s._els['dev-logo-override'].value==='','logo reset');s.onDevisLogoFileChange({target:{files:[{}]}});ok(s._els['dev-logo-override'].value==='data:image/x','custom logo file read');
console.log('\n4. Lines and totals');s._rows.length=0;var r=row('Service',2,50,'Forfait');s._rows.push(r);s._els['dev-tva-percent'].value='10';s._els['dev-timbre-amount'].value='1';s.calcDevisTotals();ok(r.map['.dev-line-total'].textContent==='100.000','line total calculated');ok(s._els['dev-total-ht'].value==='100.000','HT calculated');ok(s._els['dev-total-ttc'].value==='111.000','TTC calculated');s._rows.length=0;vm.runInContext('devisLineCount=0',s);s.addDevisLine('Added',1,3,'Km');ok(vm.runInContext('devisLineCount',s)===1,'add line increments counter');ok(s._els['dev-lines-body'].children.length===1,'line appended');s._els.removable=el('removable');s.document.getElementById=function(id){return s._els[id]||null;};s.removeDevisLine('removable');ok(s._els.removable.removed,'line removed');s._state.devis=[];s.initDevisForm();ok(s._els['dev-date'].value==='2026-08-02','new form date initialized');ok(s._els['devis-form-title'].innerHTML.indexOf('Nouveau')>=0,'new form title');
function form(x,id){x._els['dev-edit-id'].value=id||'';x._els['dev-num'].value='001/2026';x._els['dev-date'].value='2026-08-03';x._els['dev-client-name'].value='Client';x._els['dev-client-addr'].value='Addr';x._els['dev-client-mf'].value='MF';x._els['dev-total-ht'].value='100';x._els['dev-total-ttc'].value='108';x._els['dev-tva'].value='7';x._els['dev-tva-percent'].value='7';x._els['dev-timbre-amount'].value='1';x._els['dev-societe'].value='mythos';x._els['dev-logo-override'].value='';x._rows.length=0;x._rows.push(row('Service',2,50,'Forfait'));}
console.log('\n5. CRUD and preview');var c=sandbox();load(c,'js/shared/devis.js');form(c);c.saveDevis();ok(c._state.devis.length===1,'devis created');ok(c._state.devis[0].lines.length===1,'lines saved');ok(c._state.logs[0][0]==='SAVE_DEVIS','save logged');ok(c._state.views.pop()==='devis','save returns to list');var id=c._state.devis[0].id;form(c,id);c._els['dev-client-name'].value='Updated';c.saveDevis();ok(c._state.devis.length===1&&c._state.devis[0].clientName==='Updated','devis updated');c.editDevis(id);ok(c._els['dev-edit-id'].value===id,'edit id populated');ok(c._els['dev-client-name'].value==='Updated','edit client populated');ok(c._state.views.pop()==='devis-form','edit opens form');c.printDevis(id);ok(c._els['devis-preview-modal'].style.display==='flex','preview opened');ok(c._els['devis-preview'].innerHTML.indexOf('DEVIS')>=0,'preview HTML built');c.closeDevisPreview();ok(c._els['devis-preview-modal'].style.display==='none','preview closed');c.deleteDevis(id);ok(c._state.devis.length===0,'devis deleted');ok(c._state.logs.some(function(x){return x[0]==='DELETE_DEVIS';}),'delete logged');c.cancelDevisForm();ok(c._state.views.pop()==='devis','cancel returns to list');var guard=sandbox();load(guard,'js/shared/devis.js');form(guard);guard._els['dev-num'].value='';guard.saveDevis();ok(guard._state.alerts.length===1&&guard._state.devis.length===0,'number required');var cancelled=sandbox({confirm:function(){return false;}});load(cancelled,'js/shared/devis.js');cancelled._state.devis=[{id:'keep'}];cancelled.deleteDevis('keep');ok(cancelled._state.devis.length===1,'cancelled delete preserves devis');
console.log('\n6. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/devis.js')>html.indexOf('js/shared/rdvs.js'),'Devis script follows RDV');ok(html.indexOf('js/shared/devis.js')<html.indexOf('js/taches.js'),'Devis script precedes tasks');ok((app.match(/function saveDevis\(/g)||[]).length===0,'saveDevis removed from app.js');ok((app.match(/function buildDevisHTML\(/g)||[]).length===0,'buildDevisHTML removed from app.js');ok((app.match(/function nextDevisNum\(/g)||[]).length===0,'numbering removed from app.js');ok((app.match(/function printModal\(/g)||[]).length===1,'generic printModal preserved');
console.log('\nStage 4O: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
