'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',textContent:'',checked:false,style:{display:''}};}
function sandbox(overrides){var ids=['compta-cash-page','cash-link-modal','cash-link-id','cash-link-expense','cash-link-income','cash-link-bank','cash-link-title','cash-link-hint','cash-filter-status','cash-filter-min','cash-filter-max','cash-modal','cash-edit-id','cash-date','cash-amount','cash-description','cash-linked-bank'];var els={};ids.forEach(function(id){els[id]=el(id);});var state={cash:[],bank:[],expenses:[],invoices:[],saved:0,renders:0,alerts:[]};var sb={document:{getElementById:function(id){return els[id]||null;},querySelectorAll:function(){return[];}},STORE:{cashEntries:function(){return state.cash;},saveCashEntries:function(v){state.cash=v;state.saved++;},bankEntries:function(){return state.bank;},expenses:function(){return state.expenses;},invoices:function(){return state.invoices;}},_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},todayStr:function(){return'2026-08-04';},getInvoiceTotal:function(i){return Number(i.total||0);},confirm:function(){return true;},alert:function(v){state.alerts.push(v);},renderComptaViews:function(){state.renders++;},fillModalFields:function(prefix,item){els['cash-edit-id'].value=item?item.id:'';},saveModalEntity:function(prefix,getFn,saveFn,fields,renderFn,closeFn){saveFn([{id:'saved'}]);closeFn();renderFn();},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-cash.js');['renderCashPage','openCashLinkModal','closeCashLinkModal','saveCashLink','unlinkCashEntry','setComptaCashFilterStatus','setComptaCashFilterAmount','resetComptaCashFilters','getCashSelectedIds','toggleCashSelectAll','deleteCashSelected','openCashModal','closeCashModal','saveCashEntry','deleteCashEntry','fillCashLinkedBank'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});ok(vm.runInContext('comptaCashFilterStatus',s)==='all','cash status filter initialized');ok(vm.runInContext('comptaCashFilterMinAmount',s)===0,'minimum filter initialized');ok(vm.runInContext('comptaCashFilterMaxAmount',s)===Infinity,'maximum filter initialized');

console.log('\n2. Rendering and filters');s.renderCashPage();ok(s._els['compta-cash-page'].innerHTML.indexOf('Aucune entrée caisse')>=0,'empty cash page rendered');s._state.cash=[{id:'c1',date:'2026-08-01',description:'Expense <one>',amount:25,linkedType:'expense',linkedId:'e1'},{id:'c2',date:'2026-08-02',description:'Income',amount:100,linkedType:'income',linkedId:'i1'},{id:'c3',date:'2026-08-03',description:'Loose',amount:5}];s._state.expenses=[{id:'e1',label:'Fuel'}];s._state.invoices=[{id:'i1',num:'F-1'}];s.renderCashPage();ok(s._els['compta-cash-page'].innerHTML.indexOf('3 entrée(s)')>=0,'all cash entries rendered');ok(s._els['compta-cash-page'].innerHTML.indexOf('Expense &lt;one>')>=0,'description escaped');ok(s._els['compta-cash-page'].innerHTML.indexOf('Dépense: Fuel')>=0,'expense link rendered');ok(s._els['compta-cash-page'].innerHTML.indexOf('Revenu: F-1')>=0,'income link rendered');s.setComptaCashFilterStatus('expense');ok(s._els['compta-cash-page'].innerHTML.indexOf('1 entrée(s)')>=0&&s._els['compta-cash-page'].innerHTML.indexOf('Income')<0,'status filter applied');s._els['cash-filter-min'].value='30';s._els['cash-filter-max'].value='120';s.setComptaCashFilterAmount();ok(s._els['compta-cash-page'].innerHTML.indexOf('0 entrée(s)')>=0,'amount filter combines with status');s.resetComptaCashFilters();ok(s._els['compta-cash-page'].innerHTML.indexOf('3 entrée(s)')>=0,'filters reset');

console.log('\n3. Linking workflow');var l=sandbox();load(l,'js/shared/accounting-cash.js');l._state.cash=[{id:'c1',date:'2026-08-01',amount:10}];l._state.expenses=[{id:'e1',label:'Expense',amount:10}];l._state.invoices=[{id:'i1',num:'F1',total:20}];l._state.bank=[{id:'b1',type:'Retraits',date:'2026-08-01',amount:10}];l.openCashLinkModal('c1');ok(l._els['cash-link-modal'].style.display==='flex','link modal opened');ok(l._els['cash-link-expense'].innerHTML.indexOf('Expense')>=0,'expense options rendered');ok(l._els['cash-link-income'].innerHTML.indexOf('F1')>=0,'income options rendered');ok(l._els['cash-link-bank'].innerHTML.indexOf('Retraits')>=0,'bank options rendered');l._els['cash-link-expense'].value='e1';l.saveCashLink();ok(l._state.cash[0].linkedType==='expense'&&l._state.cash[0].linkedId==='e1','cash entry linked to expense');ok(l._state.saved===1,'link uses STORE write pipeline');l.unlinkCashEntry('c1');ok(!l._state.cash[0].linkedId&&!l._state.cash[0].linkedType,'cash entry unlinked');ok(l._state.saved===2,'unlink uses STORE write pipeline');var invalid=sandbox();load(invalid,'js/shared/accounting-cash.js');invalid._state.cash=[{id:'c1'}];invalid._state.expenses=[{id:'e1',label:'E'}];invalid._state.invoices=[{id:'i1',num:'I'}];invalid.openCashLinkModal('c1');invalid._els['cash-link-expense'].value='e1';invalid._els['cash-link-income'].value='i1';invalid.saveCashLink();ok(invalid._state.alerts.length===1&&invalid._state.saved===0,'multiple links rejected');

console.log('\n4. CRUD, selection, and bank list');var c=sandbox();load(c,'js/shared/accounting-cash.js');c._state.cash=[{id:'c1',date:'2026-08-01'},{id:'c2',date:'2026-08-02'}];c.document.querySelectorAll=function(q){return q==='input[name="cash-select"]:checked'?[{value:'c1'}]:[];};c.deleteCashSelected();ok(c._state.cash.length===1&&c._state.cash[0].id==='c2','bulk delete preserves unselected entry');ok(c._state.saved===1,'bulk delete uses STORE write pipeline');c.openCashModal('c2');ok(c._els['cash-edit-id'].value==='c2','edit modal receives existing entry');ok(c._els['cash-modal'].style.display==='flex','cash modal opened');c.closeCashModal();ok(c._els['cash-modal'].style.display==='none','cash modal closed');c.saveCashEntry();ok(c._state.cash[0].id==='saved','save delegates through approved modal helper');ok(c._state.renders===1,'save refreshes accounting views');c._state.cash=[{id:'delete'}];c.deleteCashEntry('delete');ok(c._state.cash.length===0,'single cash entry deleted');c._state.bank=[{id:'b1',type:'Retraits',date:'2026-08-01',amount:12},{id:'b2',type:'Versements',date:'2026-08-02',amount:50}];c.fillCashLinkedBank();ok(c._els['cash-linked-bank'].innerHTML.indexOf('b1')>=0,'withdrawal offered for cash link');ok(c._els['cash-linked-bank'].innerHTML.indexOf('b2')<0,'non-withdrawal excluded from cash link');

console.log('\n5. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/accounting-cash.js')>html.indexOf('js/shared/accounting-bank.js'),'cash script follows bank dependency');ok(html.indexOf('js/shared/accounting-cash.js')<html.indexOf('js/shared/accounting-expenses.js'),'cash script precedes expenses consumer');['renderCashPage','openCashLinkModal','saveCashLink','unlinkCashEntry','openCashModal','saveCashEntry','fillCashLinkedBank'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok((app.match(/let comptaCashFilterStatus/g)||[]).length===0,'cash filter state removed from app.js');ok(app.indexOf('function renderStatistique(')>=0,'statistics workflow remains in app.js');

console.log('\nStage 4Q: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
