'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id,type){return{id:id,type:type||'text',value:'',innerHTML:'',checked:false,style:{display:''}};}
function sandbox(overrides){var ids=['compta-purchases-page','purchase-modal','purchase-edit-id','purchase-num','purchase-date','purchase-supplier-id','purchase-supplier-name','purchase-payment','purchase-status','purchase-category','purchase-amount','purchase-tva','purchase-tva19Amount','purchase-tva13Amount','purchase-tva7Amount','purchase-notes','purchase-addStamp','purchase-addSignature'];var els={};ids.forEach(function(id){els[id]=el(id,id.indexOf('amount')>=0||id.indexOf('Amount')>=0?'number':'text');});var state={purchases:[],suppliers:[],saved:0,renders:0,calculations:0,alerts:[]};var sb={event:{stopPropagation:function(){}},document:{getElementById:function(id){return els[id]||null;},querySelectorAll:function(){return[];}},STORE:{purchases:function(){return state.purchases;},savePurchases:function(v){state.purchases=v;state.saved++;},suppliers:function(){return state.suppliers;}},_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},todayStr:function(){return'2026-08-04';},confirm:function(){return true;},alert:function(v){state.alerts.push(v);},renderComptaViews:function(){state.renders++;},calculateFromTTC:function(){state.calculations++;},setTimeout:function(fn){fn();},fillModalFields:function(prefix,item){els['purchase-edit-id'].value=item?item.id:'';if(item){els['purchase-num'].value=item.num||'';els['purchase-supplier-id'].value=item.supplierId||'';}},saveModalEntity:function(prefix,getFn,saveFn,fields,renderFn,closeFn){saveFn([{id:'saved'}]);closeFn();renderFn();},console:{log:function(){},warn:function(){},error:function(){}},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity,parseInt:parseInt};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-purchases.js');['getPurchaseSelectedIds','togglePurchaseSelectAll','deletePurchaseSelected','getCategoryIcon','renderPurchasesPage','getNextPurchaseNum','openPurchaseModal','closePurchaseModal','savePurchase','deletePurchase','fillPurchaseSuppliers','syncPurchaseSupplier'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});

console.log('\n2. Numbering and rendering');ok(s.getNextPurchaseNum()==='ACH-001','first purchase number');s._state.purchases=[{id:'p1',num:'ACH-002',date:'2026-08-01',supplierName:'Supplier <A>',notes:'Parts',payment:'BIAT',category:'Matériel',amount:120,tva19Amount:10,tva13Amount:2,tva7Amount:1},{id:'p2',num:'LEGACY',date:'2026-08-02',supplierName:'Other',amount:30}];ok(s.getNextPurchaseNum()==='ACH-003','next purchase number ignores legacy values');s.renderPurchasesPage();ok(s._els['compta-purchases-page'].innerHTML.indexOf('ACH-002')>=0,'purchase number rendered');ok(s._els['compta-purchases-page'].innerHTML.indexOf('Supplier &lt;A>')>=0,'supplier escaped');ok(s._els['compta-purchases-page'].innerHTML.indexOf('13.000')>=0,'TVA components totaled');ok(s._els['compta-purchases-page'].innerHTML.indexOf('120.000')>=0,'purchase amount rendered');ok(s.getCategoryIcon('Matériel')==='🔧','known category icon preserved');ok(s.getCategoryIcon('Unknown')==='📋','fallback category icon preserved');var empty=sandbox();load(empty,'js/shared/accounting-purchases.js');empty.renderPurchasesPage();ok(empty._els['compta-purchases-page'].innerHTML.indexOf('Aucune donnee')>=0,'empty purchases page rendered');

console.log('\n3. Selection and deletion');var b=sandbox();load(b,'js/shared/accounting-purchases.js');b._state.purchases=[{id:'p1'},{id:'p2'}];b.document.querySelectorAll=function(q){return q==='input[name="purchase-select"]:checked'?[{value:'p1'}]:[];};b.deletePurchaseSelected();ok(b._state.purchases.length===1&&b._state.purchases[0].id==='p2','bulk delete preserves unselected purchase');ok(b._state.saved===1,'bulk delete uses STORE write pipeline');ok(b._state.renders===1,'bulk delete refreshes accounting views');var none=sandbox();load(none,'js/shared/accounting-purchases.js');none.deletePurchaseSelected();ok(none._state.alerts.length===1,'bulk delete requires selection');var boxes=[{checked:false},{checked:false}];none.document.querySelectorAll=function(){return boxes;};none.togglePurchaseSelectAll(true);ok(boxes.every(function(x){return x.checked;}),'select all toggles purchase checkboxes');

console.log('\n4. Supplier synchronization');var u=sandbox();load(u,'js/shared/accounting-purchases.js');u._state.suppliers=[{id:'s1',name:'Supplier <One>',payment:'Cash'},{id:'s2',name:'Second'}];u.fillPurchaseSuppliers();ok(u._els['purchase-supplier-id'].innerHTML.indexOf('Supplier &lt;One>')>=0,'supplier options escaped');u._els['purchase-supplier-id'].value='s1';u.syncPurchaseSupplier();ok(u._els['purchase-supplier-name'].value==='Supplier <One>','supplier name synchronized');ok(u._els['purchase-payment'].value==='Cash','supplier payment synchronized');u._els['purchase-supplier-id'].value='s2';u.syncPurchaseSupplier();ok(u._els['purchase-payment'].value==='BIAT','default supplier payment preserved');

console.log('\n5. Purchase CRUD and form');var c=sandbox();load(c,'js/shared/accounting-purchases.js');c._state.suppliers=[{id:'s1',name:'Supplier'}];c.openPurchaseModal();ok(c._els['purchase-num'].value==='ACH-001','new form gets next number');ok(c._els['purchase-tva'].value==='19','new form gets default TVA');ok(c._els['purchase-date'].value==='2026-08-04','new form gets current date');ok(c._els['purchase-modal'].style.display==='flex','purchase modal opened');ok(c._state.calculations===1,'purchase totals initialized at existing timing');c.closePurchaseModal();ok(c._els['purchase-modal'].style.display==='none','purchase modal closed');c.savePurchase();ok(c._state.purchases[0].id==='saved','save delegates through approved modal helper');ok(c._state.saved===1,'purchase save uses STORE write pipeline');ok(c._state.renders===1,'purchase save refreshes accounting views');c._state.purchases=[{id:'delete'}];c.deletePurchase('delete');ok(c._state.purchases.length===0,'purchase deleted');ok(c._state.saved===2,'purchase delete uses STORE write pipeline');var edit=sandbox();load(edit,'js/shared/accounting-purchases.js');edit._state.purchases=[{id:'p1',num:'ACH-009',supplierId:'s1'}];edit._state.suppliers=[{id:'s1',name:'Supplier'}];edit.openPurchaseModal('p1');ok(edit._els['purchase-edit-id'].value==='p1','existing purchase loaded');ok(edit._els['purchase-num'].value==='ACH-009','existing number preserved');

console.log('\n6. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/accounting-purchases.js')>html.indexOf('js/shared/accounting-expenses.js'),'purchases script follows accounting dependencies');ok(html.indexOf('js/shared/accounting-purchases.js')<html.indexOf('js/taches.js'),'purchases script precedes consumers');['getPurchaseSelectedIds','renderPurchasesPage','getNextPurchaseNum','openPurchaseModal','savePurchase','fillPurchaseSuppliers','syncPurchaseSupplier'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok(app.indexOf('function renderSuppliersPage(')>=0,'supplier management remains in app.js');ok(app.indexOf('function renderStatistique(')>=0,'statistics workflow remains in app.js');ok(app.indexOf('function generateMonthlyReport(')>=0,'broader financial report remains in app.js');ok(app.indexOf('function getSupplierCategoryStyle(')>=0,'supplier category styling remains in app.js');

console.log('\nStage 4S: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
