'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0,RealDate=Date;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function FakeDate(){var args=Array.prototype.slice.call(arguments);return args.length?new (Function.prototype.bind.apply(RealDate,[null].concat(args)))():new RealDate('2026-08-15T12:00:00Z');}FakeDate.now=RealDate.now;FakeDate.parse=RealDate.parse;FakeDate.UTC=RealDate.UTC;FakeDate.prototype=RealDate.prototype;
function sandbox(overrides){var el={innerHTML:''},state={invoices:[],rdvs:[],clients:[],oms:[],representations:[],expenses:[],bank:[],contracts:[],storeReads:0};var sb={document:{getElementById:function(id){return id==='statistique-dashboard'?el:null;}},STORE:{invoices:function(){state.storeReads++;return state.invoices;},rdvs:function(){return state.rdvs;},clients:function(){return state.clients;},oms:function(){return state.oms;},representations:function(){return state.representations;},expenses:function(){return state.expenses;},bankEntries:function(){return state.bank;},contracts:function(){return state.contracts;}},_el:el,_state:state,normalizeRdv:function(v){return v;},getInvoiceTotal:function(v){return Number(v.total||0);},getRdvAmount:function(v){return Number(v.amount||0);},num:function(v){var n=Number(v||0);return Number.isFinite(n)?n:0;},fmtMoney:function(v){return Number(v||0).toFixed(3);},escapeHtml:function(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;');},_statKpi:function(icon,label,value,color){return'<kpi data-label="'+label+'" data-color="'+color+'">'+icon+value+'</kpi>';},_statMini:function(label,value,suffix){return'<mini data-label="'+label+'">'+value+' '+suffix+'</mini>';},Date:FakeDate,Math:Math,Number:Number,String:String,Array:Array,Object:Object,console:{log:function(){},warn:function(){},error:function(){}}};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported global and missing DOM');var s=sandbox();load(s,'js/shared/statistics-dashboard.js');ok(typeof s.renderStatistique==='function','renderStatistique is global');var missing=sandbox();missing.document.getElementById=function(){return null;};load(missing,'js/shared/statistics-dashboard.js');missing.renderStatistique();ok(missing._state.storeReads===0,'missing dashboard exits before data reads');

console.log('\n2. Empty dashboard');s.renderStatistique();var html=s._el.innerHTML;ok(html.indexOf('Production totale')>=0,'production KPI rendered');ok(html.indexOf('0.000 TND')>=0,'zero totals formatted');ok(html.indexOf('0%')>=0,'zero recovery percentage rendered');ok(html.indexOf('Aucune donnée')>=0,'empty top-client state rendered');ok(html.indexOf('Taux de recouvrement')>=0,'recovery section rendered');ok(html.indexOf('Activité mensuelle')>=0,'monthly activity section rendered');ok(html.indexOf('Évolution des dépenses')>=0,'expense trend section rendered');ok(html.indexOf('<svg')>=0,'SVG charts rendered');ok(html.indexOf('<polyline')>=0,'expense line rendered');ok(html.indexOf('Factures')>=0&&html.indexOf('0 total')>=0,'empty invoice count rendered');

console.log('\n3. Aggregations and KPIs');var d=sandbox();load(d,'js/shared/statistics-dashboard.js');d._state.invoices=[{id:'i1',clientName:'Alpha',date:'2026-08-02',status:'paid',total:100},{id:'i2',clientName:'Beta',date:'2026-08-03',status:'pending',total:50},{id:'i3',clientName:'Legacy',date:'2020-01-01',status:'pending',total:200}];d._state.rdvs=[{id:'r1',clientName:'Alpha',date:'2026-08-04',amount:40},{id:'r2',clientName:'<Risk>',startDate:'2026-07-10',amount:60}];d._state.clients=[{id:'c1'},{id:'c2'}];d._state.oms=[{id:'o1'}];d._state.representations=[{id:'rep1',fee:30},{id:'rep2',fee:'bad'}];d._state.expenses=[{id:'e1',date:'2026-08-05',amount:25},{id:'e2',date:'2020-01-01',amount:75},{id:'e3',date:'2026-08-06',amount:'bad'}];d._state.contracts=[{id:'ct1'},{id:'ct2'},{id:'ct3'}];d.renderStatistique();html=d._el.innerHTML;ok(html.indexOf('450.000 TND')>=0,'production totals invoices and calendar');ok(html.indexOf('100.000 TND')>=0,'paid invoice total rendered');ok(html.indexOf('250.000 TND')>=0,'unpaid invoice total rendered');ok(html.indexOf('100.000 TND')>=0,'expense total rendered');ok(html.indexOf('30.000 TND')>=0,'representation total rendered');ok(html.indexOf('29%')>=0,'recovery percentage rounded');ok(html.indexOf('Alpha')>=0,'top client rendered');ok(html.indexOf('&lt;Risk>')>=0,'top client name escaped');ok(html.indexOf('200.000')>=0,'top-client values include historical data');ok(html.indexOf('3 total')>=0,'invoice count rendered');ok(html.indexOf('2 actifs')>=0,'client count rendered');ok(html.indexOf('3 signés')>=0,'contract count rendered');ok(html.indexOf('1 émis')>=0,'mission-order count rendered');ok(html.indexOf('2 planifiés')>=0,'calendar count rendered');ok(html.indexOf('2 enregistrées')>=0,'representation count rendered');ok(html.indexOf('3</mini>')<0,'mini markup preserves suffix inside element');

console.log('\n4. Monthly datasets and charts');ok((html.match(/<rect /g)||[]).length>=1,'monthly bar dataset rendered');ok((html.match(/<circle /g)||[]).length>=12,'donut and monthly expense points rendered');ok(html.indexOf('140')>=0,'current-month invoice and RDV activity combined');ok(html.indexOf('25')>=0,'current-month expense point represented');ok(html.indexOf('barGrad')>=0,'bar gradient contract preserved');ok(html.indexOf('stroke="#ef4444"')>=0,'expense line styling preserved');ok(html.indexOf('transition:width 0.5s')>=0,'top-client comparison bars preserved');

console.log('\n5. Partial data and optional contracts');var partial=sandbox();delete partial.STORE.contracts;load(partial,'js/shared/statistics-dashboard.js');partial._state.invoices=[{date:'',clientName:'',status:'paid',total:10}];partial.renderStatistique();html=partial._el.innerHTML;ok(html.indexOf('10.000 TND')>=0,'partial invoice data rendered');ok(html.indexOf('Inconnu')>=0,'missing client uses legacy fallback');ok(html.indexOf('Contrats')>=0&&html.indexOf('0 signés')>=0,'optional contracts reader falls back to empty');ok((function(){try{partial.renderStatistique();return true;}catch(e){return false;}})(),'repeated render remains safe');

console.log('\n6. Integration and lifecycle exclusions');var index=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),router=fs.readFileSync(path.join(BASE,'js/core/router.js'),'utf8'),module=fs.readFileSync(path.join(BASE,'js/shared/statistics-dashboard.js'),'utf8');ok(index.indexOf('js/shared/statistics-dashboard.js')>index.indexOf('js/shared/accounting-overview.js'),'statistics script follows data dependencies');ok(index.indexOf('js/shared/statistics-dashboard.js')<index.indexOf('js/taches.js'),'statistics script precedes trailing consumer');ok(app.indexOf('function renderStatistique(')<0,'statistics dashboard removed from app.js');ok((module.match(/function renderStatistique\(/g)||[]).length===1,'statistics global defined once');ok(router.indexOf("if (view === 'statistique') renderStatistique()")>=0,'router compatibility call preserved');ok(index.indexOf('onclick="renderStatistique()"')>=0,'manual refresh contract preserved');ok(module.indexOf('new Chart(')<0,'no chart instance introduced');ok(module.indexOf('addEventListener')<0,'no listener introduced');ok(module.indexOf('localStorage')<0,'statistics remains read-only');ok(app.indexOf('function renderEntityPage(')>=0,'generic entity renderer remains in app.js');ok(app.indexOf('function closeModalFromOutsideClick(')>=0,'modal overlay behavior remains in app.js');

console.log('\nStage 4Y: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
