'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function el(id){return{id:id,value:'',innerHTML:'',textContent:'',checked:false,style:{display:''},querySelectorAll:function(){return[];}};}
function sandbox(overrides){var ids=['compta-bank-page','bank-modal','bank-edit-id','bank-date','bank-type','bank-label','bank-amount','bank-balance','bank-filter-min','bank-filter-max','bank-detail-modal','bank-link-modal','import-results-modal'];var els={};ids.forEach(function(id){els[id]=el(id);});var state={bank:[],saved:0,renders:0,alerts:[]};var sb={window:null,event:{stopPropagation:function(){}},document:{getElementById:function(id){return els[id]||null;},querySelectorAll:function(){return[];}},STORE:{bankEntries:function(){return state.bank;},saveBankEntries:function(v){state.bank=v;state.saved++;},expenses:function(){return[];},invoices:function(){return[];},contracts:function(){return[];},suppliers:function(){return[];}},_els:els,_state:state,esc:function(v){return String(v==null?'':v).replace(/</g,'&lt;');},num:function(v){return Number(v||0);},fmtMoney:function(v){return Number(v||0).toFixed(3);},todayStr:function(){return'2026-08-04';},confirm:function(){return true;},alert:function(v){state.alerts.push(v);},console:{log:function(){},warn:function(){},error:function(){}},renderComptaViews:function(){state.renders++;},fillModalFields:function(prefix,item){els['bank-edit-id'].value=item?item.id:'';},saveModalEntity:function(prefix,getFn,saveFn,fields,renderFn,closeFn){saveFn([{id:'saved'}]);closeFn();renderFn();},getInvoiceTotal:function(){return 0;},contractTotals:function(){return{totalTTC:0};},Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Infinity:Infinity,parseFloat:parseFloat,isNaN:isNaN};sb.window=sb;Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/accounting-bank.js');['cleanupBankEntryTypes','getBankTypeIcon','openBankDetailModal','closeBankDetailModal','openBankLinkModal','closeBankLinkModal','saveBankLink','unlinkBankEntry','getBankSelectedIds','toggleBankSelectAll','deleteBankSelected','renderBankPage','setComptaBankFilterType','setComptaBankFilterStatus','setComptaBankFilterAmount','setComptaBankFilterReference','resetComptaBankFilters','openBankModal','closeBankModal','saveBankEntry','deleteBankEntry','importBankFile','displayImportResults','closeImportResults'].forEach(function(n){ok(typeof s[n]==='function',n+' is global');});ok(typeof s.fixBankTypes==='function','manual cleanup compatibility global');

console.log('\n2. Cleanup and icon behavior');s._state.bank=[{id:'bad',type:'2026-08-04'},{id:'good',type:'Virements'}];s.cleanupBankEntryTypes();ok(s._state.bank[0].type==='Opération','date-shaped type cleaned');ok(s._state.bank[1].type==='Virements','valid type preserved');ok(s._state.saved===1,'cleanup uses STORE write pipeline');ok(s.getBankTypeIcon('Virements')==='🔄','known bank icon preserved');ok(s.getBankTypeIcon('unknown')==='📋','fallback bank icon preserved');ok(s.getBankTypeIcon('2026/08/04')==='📋','invalid date type normalized for icon');

console.log('\n3. Page, filtering, and selection');var p=sandbox();load(p,'js/shared/accounting-bank.js');p.renderBankPage();ok(p._els['compta-bank-page'].innerHTML.indexOf('Aucune donnee')>=0,'empty bank page rendered');p._state.bank=[{id:'b1',date:'2026-08-01',type:'Retraits',label:'Supplier <A>',amount:100,balance:900,direction:'Debit',reference:'REF-1'},{id:'b2',date:'2026-08-02',type:'Versements',label:'Income',amount:200,balance:1100,direction:'Credit',reference:'REF-2'}];p.renderBankPage();ok(p._els['compta-bank-page'].innerHTML.indexOf('2 transaction(s)')>=0,'all bank entries rendered');ok(p._els['compta-bank-page'].innerHTML.indexOf('Retraits')>=0&&p._els['compta-bank-page'].innerHTML.indexOf('Versements')>=0,'bank types rendered');p.setComptaBankFilterType('retrait');ok(p._els['compta-bank-page'].innerHTML.indexOf('1 transaction(s)')>=0&&p._els['compta-bank-page'].innerHTML.indexOf('Versements')<0,'direction filter applied');p.setComptaBankFilterReference('income');ok(p._els['compta-bank-page'].innerHTML.indexOf('0 transaction(s)')>=0,'reference filter combines with direction');p.resetComptaBankFilters();ok(p._els['compta-bank-page'].innerHTML.indexOf('2 transaction(s)')>=0,'filters reset');p.document.querySelectorAll=function(q){return q==='input[name="bank-select"]:checked'?[{value:'b1'}]:[];};p.deleteBankSelected();ok(p._state.bank.length===1&&p._state.bank[0].id==='b2','bulk delete preserves unselected entry');ok(p._state.saved===1,'bulk delete uses STORE write pipeline');

console.log('\n4. CRUD and modals');var c=sandbox();load(c,'js/shared/accounting-bank.js');c._state.bank=[{id:'b1',date:'2026-08-01'}];c.openBankModal('b1');ok(c._els['bank-edit-id'].value==='b1','edit modal receives existing entry');ok(c._els['bank-modal'].style.display==='flex','bank modal opened');c.closeBankModal();ok(c._els['bank-modal'].style.display==='none','bank modal closed');c.saveBankEntry();ok(c._state.bank[0].id==='saved','save delegates through approved modal write helper');ok(c._state.renders===1,'save refreshes accounting views');c._state.bank=[{id:'delete'}];c.deleteBankEntry('delete');ok(c._state.bank.length===0,'single bank entry deleted');c._state.bank=[{id:'detail',date:'2026-08-01',type:'Retraits',label:'Test',amount:10,direction:'Debit'}];c.openBankDetailModal('detail');ok(c._els['bank-detail-modal'].style.display==='flex','detail modal opened');ok(c._els['bank-detail-modal'].innerHTML.indexOf('Détails de la Transaction')>=0,'detail content rendered');c.closeBankDetailModal();ok(c._els['bank-detail-modal'].style.display==='none','detail modal closed');

console.log('\n5. Integration');var html=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8');ok(html.indexOf('js/shared/accounting-bank.js')>html.indexOf('js/shared/devis.js'),'bank script follows extracted dependencies');ok(html.indexOf('js/shared/accounting-bank.js')<html.indexOf('js/shared/accounting-cash.js'),'bank script precedes cash consumer');['cleanupBankEntryTypes','renderBankPage','openBankDetailModal','openBankModal','saveBankEntry','importBankFile'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');});ok((app.match(/let comptaBankFilterType/g)||[]).length===0,'bank filter state removed from app.js');ok(html.indexOf('js/shared/accounting-expenses.js')>html.indexOf('js/shared/accounting-cash.js'),'expenses module follows accounting dependencies');

console.log('\nStage 4P: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
