'use strict';
var vm=require('vm'),fs=require('fs'),path=require('path'),BASE=path.join(__dirname,'..'),pass=0,fail=0;
function ok(v,l){if(v){pass++;console.log('  PASS '+l);}else{fail++;console.log('  FAIL '+l);}}
function field(type,value){return{type:type||'text',value:value==null?'':String(value),checked:false};}
function sandbox(overrides){var els={'entity-edit-id':field(),'entity-name':field(),'entity-amount':field('number'),'entity-enabled':field('checkbox'),'entity-supplier-id':field(),'entity-supplier-name':field(),'entity-linked-bank':field(),'entity-plain-field':field()},state={items:[],saved:null,order:[]};var FakeDate={now:function(){return 4242;}};var sb={document:{getElementById:function(id){return Object.prototype.hasOwnProperty.call(els,id)?els[id]:null;}},_els:els,_state:state,num:function(v){return Number(v||0);},Date:FakeDate,console:{log:function(){},warn:function(){},error:function(){}},Number:Number,String:String,Array:Array,Object:Object};Object.assign(sb,overrides||{});return vm.createContext(sb);}
function load(s,f){vm.runInContext(fs.readFileSync(path.join(BASE,f),'utf8'),s);}

console.log('\n1. Exported globals');var s=sandbox();load(s,'js/shared/modal-entity-helpers.js');ok(typeof s.fillModalFields==='function','fillModalFields is global');ok(typeof s.saveModalEntity==='function','saveModalEntity is global');

console.log('\n2. Form population and key mapping');var item={id:'e1',name:'Alpha',amount:0,enabled:false,supplierId:'s1',supplierName:'Supplier',linkedBank:'b1',plainfield:'Plain'};s.fillModalFields('entity',item,['name','amount','enabled','supplier-id','supplier-name','linked-bank','plain-field','missing']);ok(s._els['entity-edit-id'].value==='e1','edit id populated');ok(s._els['entity-name'].value==='Alpha','text populated');ok(s._els['entity-amount'].value===0,'zero value preserved');ok(s._els['entity-enabled'].checked===false,'false checkbox preserved');ok(s._els['entity-supplier-id'].value==='s1','supplier id mapping preserved');ok(s._els['entity-supplier-name'].value==='Supplier','supplier name mapping preserved');ok(s._els['entity-linked-bank'].value==='b1','linked bank mapping preserved');ok(s._els['entity-plain-field'].value==='Plain','single-dash generic mapping preserved');

console.log('\n3. Reset and fallback population');s._els['entity-name'].value='stale';s._els['entity-enabled'].checked=true;s.fillModalFields('entity',null,['name','enabled']);ok(s._els['entity-edit-id'].value==='','new entity clears edit id');ok(s._els['entity-name'].value==='','new entity clears text');ok(s._els['entity-enabled'].checked===false,'new entity clears checkbox');s.fillModalFields('entity',{id:'e2','plain-field':'Fallback'},['plain-field']);ok(s._els['entity-plain-field'].value==='Fallback','raw field fallback preserved');ok((function(){try{s.fillModalFields('entity',{id:'e3'},['missing']);return true;}catch(e){return false;}})(),'missing optional field ignored');

console.log('\n4. Create and serialization');var c=sandbox();load(c,'js/shared/modal-entity-helpers.js');c._els['entity-name'].value='Created';c._els['entity-amount'].value='12.75';c._els['entity-enabled'].checked=true;c._els['entity-supplier-id'].value='s9';c._els['entity-supplier-name'].value='Vendor';c._els['entity-linked-bank'].value='b9';function getCreate(){c._state.order.push('get');return c._state.items;}function saveCreate(v){c._state.order.push('save');c._state.saved=v;}function closeCreate(){c._state.order.push('close');}function renderCreate(){c._state.order.push('render');}c.saveModalEntity('entity',getCreate,saveCreate,['name','amount','enabled','supplier-id','supplier-name','linked-bank','missing'],renderCreate,closeCreate);var created=c._state.saved[0];ok(created.id==='entity_4242','generated id preserves prefix and timestamp');ok(created.name==='Created','text serialized');ok(created.amount===12.75,'number coerced through num helper');ok(created.enabled===true,'checkbox serialized');ok(created.supplierId==='s9','supplier id serialized to mapped key');ok(created.supplierName==='Vendor','supplier name serialized to mapped key');ok(created.linkedBank==='b9','linked bank serialized to mapped key');ok(created.missing==='','missing field serializes as empty string');ok(c._state.order.join(',')==='get,save,close,render','writer, close, and render callback order preserved');

console.log('\n5. Update and approved writer callback');var u=sandbox();load(u,'js/shared/modal-entity-helpers.js');u._state.items=[{id:'keep',name:'Keep'},{id:'edit',name:'Old',legacy:'drop'}];u._els['entity-edit-id'].value='edit';u._els['entity-name'].value='Updated';u._els['entity-amount'].value='not-a-number';u._els['entity-enabled'].checked=false;var writes=0;u.saveModalEntity('entity',function(){return u._state.items;},function(v){writes++;u._state.saved=v;},['name','amount','enabled'],function(){u._state.order.push('render');},function(){u._state.order.push('close');});ok(u._state.saved.length===2,'update does not duplicate entity');ok(u._state.saved[0].id==='keep','unrelated entity preserved');var updated=u._state.saved[1];ok(updated.id==='edit','existing id preserved');ok(updated.name==='Updated','existing text updated');ok(Number.isNaN(updated.amount),'existing numeric coercion behavior preserved');ok(updated.enabled===false,'unchecked value serialized');ok(!Object.prototype.hasOwnProperty.call(updated,'legacy'),'replacement object behavior preserved');ok(writes===1,'provided STORE writer invoked once');ok(u._state.order.join(',')==='close,render','close precedes render after update');

console.log('\n6. Integration and exclusions');var index=fs.readFileSync(path.join(BASE,'index.html'),'utf8'),app=fs.readFileSync(path.join(BASE,'js/app.js'),'utf8'),helper=fs.readFileSync(path.join(BASE,'js/shared/modal-entity-helpers.js'),'utf8');var consumers=['accounting-bank.js','accounting-cash.js','accounting-expenses.js','accounting-purchases.js','accounting-suppliers.js'];ok(index.indexOf('js/shared/modal-entity-helpers.js')>index.indexOf('js/app.js'),'helper script follows num dependency');consumers.forEach(function(file){ok(index.indexOf('js/shared/modal-entity-helpers.js')<index.indexOf('js/shared/'+file),file+' loads after helper');});['fillModalFields','saveModalEntity'].forEach(function(n){ok(app.indexOf('function '+n+'(')<0,n+' removed from app.js');ok((helper.match(new RegExp('function '+n+'\\(','g'))||[]).length===1,n+' defined once in helper module');});ok(helper.indexOf('addEventListener')<0,'helper introduces no listeners');ok(helper.indexOf('localStorage')<0,'helper introduces no storage bypass');ok(helper.indexOf('confirm(')<0,'entity confirmation remains outside generic helper');ok(helper.indexOf('delete')<0,'entity deletion remains outside generic helper');ok(app.indexOf('function renderEntityPage(')>=0,'generic entity renderer remains in app.js');ok(app.indexOf('function renderStatistique(')>=0,'statistics remain in app.js');

console.log('\nStage 4X: '+pass+' passed, '+fail+' failed');if(fail)process.exit(1);
