-- 0015-contact-import.sql — Phase 11 (P2 Contact import / dedup — "Répertoire").
-- Discovery evidence (legacy repo root, js/shared/contacts.js, plugins/
-- contacts.*): the legacy "Répertoire de contacts" imported contacts from the
-- phone (Contact Picker API), from a vCard file, or from Google (server-side
-- OAuth, PHP), kept an import HISTORY (mp_repertoire_imports: id, date, count,
-- label, source) so a batch could be filtered or deleted as a whole, detected
-- DUPLICATES on identical tel1 or email, merged a group into its first member
-- (empty fields filled from the others), and exported a CSV whose header is
-- Nom, Prénom, Téléphone 1, Téléphone 2, Email, Ville, Métier, Domaine, …,
-- Note. Per-contact fields: nom, prenom, adresse, ville, gouvernorat, pays,
-- tel1, tel2, email, metier, domaine, note (+ CRM history/tags/follow-up).
-- What is reproduced: file import (vCard + CSV, the legacy CSV header
-- included), import batches with label/counts and whole-batch retirement,
-- duplicate detection on phone-or-email, merge into the first contact.
-- What is NOT reproduced, and why: the phone Contact Picker (browser API,
-- the client can still export a .vcf); the Google OAuth PHP flow (the master
-- order forbids reviving legacy PHP endpoints; a Google CSV export imports
-- through the CSV path); CRM call history / outcomes / tags / follow-ups
-- (agenda_events already carries reminders and tasks linked to a client;
-- classified NOT_REQUIRED for completion, evidence in the handover).
-- Architecture: REUSE the existing `contacts` table (schema.sql already maps
-- it to legacy mp_repertoire_contacts), EXTEND it with the legacy fields it
-- lacked, and ADD one small `contact_imports` table for the batch history.
-- Duplicate keys are computed by the database (a generated, indexed
-- phone_norm — digits and a leading + only, the legacy _rcCleanPhone rule)
-- so the API never keeps a second copy of the truth. Module: the existing
-- 'clients' module and its clients.read / clients.write / clients.delete
-- permissions — no new tenant_modules key, no new permission, no new role.
-- No accounting effect.

BEGIN;

CREATE TABLE contact_imports (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid NOT NULL REFERENCES tenants(id),
    source          text NOT NULL,                     -- vcard | csv
    label           text,
    file_name       text,
    row_count       integer NOT NULL DEFAULT 0,        -- rows found in the file
    imported_count  integer NOT NULL DEFAULT 0,        -- contacts created
    skipped_count   integer NOT NULL DEFAULT 0,        -- duplicates / invalid rows left out
    created_by      uuid REFERENCES users(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    CONSTRAINT contact_imports_source_known CHECK (source IN ('vcard', 'csv')),
    CONSTRAINT contact_imports_counts_sane CHECK (row_count >= 0 AND imported_count >= 0 AND skipped_count >= 0)
);

CREATE INDEX contact_imports_tenant_idx ON contact_imports (tenant_id);
CREATE INDEX contact_imports_created_idx ON contact_imports (created_at DESC) WHERE deleted_at IS NULL;

ALTER TABLE contact_imports ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON contact_imports
    USING (tenant_id = current_tenant())
    WITH CHECK (tenant_id = current_tenant());

CREATE TRIGGER contact_imports_set_updated_at BEFORE UPDATE ON contact_imports
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Legacy répertoire fields the current contacts row lacked. All nullable,
-- no default that rewrites existing rows.
ALTER TABLE contacts
    ADD COLUMN phone2     text,
    ADD COLUMN address    text,
    ADD COLUMN city       text,
    ADD COLUMN country    text,
    ADD COLUMN job_title  text,                        -- legacy métier
    ADD COLUMN domain     text,                        -- legacy domaine / organisation
    ADD COLUMN notes      text,
    ADD COLUMN import_id  uuid REFERENCES contact_imports(id),
    -- Duplicate key: digits and a leading '+' only (legacy _rcCleanPhone).
    -- Generated by the database so every writer — generic registry CRUD,
    -- the importer, a future migration — yields the same key.
    ADD COLUMN phone_norm text GENERATED ALWAYS AS (
        nullif(regexp_replace(coalesce(phone, ''), '[^0-9+]', '', 'g'), '')
    ) STORED;

CREATE INDEX contacts_phone_norm_idx ON contacts (tenant_id, phone_norm)
    WHERE deleted_at IS NULL AND phone_norm IS NOT NULL;
CREATE INDEX contacts_email_idx ON contacts (tenant_id, email)
    WHERE deleted_at IS NULL AND email IS NOT NULL;
CREATE INDEX contacts_import_idx ON contacts (import_id) WHERE import_id IS NOT NULL;

-- Two new audit actions (lib/audit.js ACTIONS is the mirror): a preview
-- records that a file of personal data crossed the API (never its contents),
-- a merge records which contacts were folded into which. The CHECK is the
-- explicit list schema-tenant.sql installed; a migration redefines it whole
-- because an applied file is never edited (the runner refuses a changed
-- checksum) — the same reasoning schema-tenant.sql gives for itself.
ALTER TABLE audit_log DROP CONSTRAINT audit_action_known;
ALTER TABLE audit_log ADD CONSTRAINT audit_action_known CHECK (action IN (
    'login.success','login.failure','logout','session.revoked',
    'password.reset_requested','password.reset_completed','password.changed',
    'mfa.enabled','mfa.disabled',
    'record.created','record.updated','record.deleted','record.restored',
    'permission.denied','role.assigned','role.revoked',
    'user.created','user.disabled','user.enabled',
    'export','backup.created','backup.restored',
    'tenant.switched','tenant.created','tenant.updated',
    'module.enabled','module.disabled',
    'membership.granted','membership.revoked',
    'contacts.import_previewed','contacts.merged'
));

-- Guarded exactly like 0004/0006/0010/0013/0014: the throwaway test drills
-- create erp_app AFTER running migrations. contacts itself was granted by
-- schema.sql's blanket grant; the new table needs its own.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_app') THEN
    GRANT SELECT, INSERT, UPDATE ON contact_imports TO erp_app;
  END IF;
END $$;

COMMIT;
