-- MYTHOS WP — migration 0007 rollback (drops V2 tables; keeps data in pre-V2 tables intact)
DROP TABLE IF EXISTS wp_notes;
DROP TABLE IF EXISTS wp_automation_runs;
DROP TABLE IF EXISTS wp_automations;
DROP TABLE IF EXISTS wp_health_checks;
DROP TABLE IF EXISTS wp_integrations;
DROP TABLE IF EXISTS wp_templates;
ALTER TABLE wp_handoffs DROP CONSTRAINT IF EXISTS wp_handoffs_direction_domain;
ALTER TABLE wp_handoffs DROP COLUMN IF EXISTS previous_state, DROP COLUMN IF EXISTS taken_at, DROP COLUMN IF EXISTS taken_by, DROP COLUMN IF EXISTS direction;
ALTER TABLE wp_ai_runs DROP CONSTRAINT IF EXISTS wp_ai_runs_kind_domain;
ALTER TABLE wp_ai_runs ADD CONSTRAINT wp_ai_runs_kind_domain CHECK (kind IN ('suggest', 'auto_reply', 'classify', 'transcribe', 'vision', 'summarize'));
ALTER TABLE wp_ai_runs DROP COLUMN IF EXISTS tools_used, DROP COLUMN IF EXISTS agent_id;
ALTER TABLE wp_conversations DROP CONSTRAINT IF EXISTS wp_conversations_agent_fk;
ALTER TABLE wp_conversations DROP CONSTRAINT IF EXISTS wp_conversations_handler_domain;
ALTER TABLE wp_conversations DROP COLUMN IF EXISTS agent_id, DROP COLUMN IF EXISTS handler, DROP COLUMN IF EXISTS route_rule_id, DROP COLUMN IF EXISTS routed_by;
DROP TABLE IF EXISTS wp_project_agents;
DROP TABLE IF EXISTS wp_agents;
DELETE FROM wp_inbox_routes WHERE kind IN ('keyword', 'default');
ALTER TABLE wp_inbox_routes DROP CONSTRAINT IF EXISTS wp_inbox_routes_value_shape;
ALTER TABLE wp_inbox_routes ADD CONSTRAINT wp_inbox_routes_value_shape CHECK (identity_value ~ '^[A-Za-z0-9:_.@+-]{3,128}$');
ALTER TABLE wp_inbox_routes DROP CONSTRAINT IF EXISTS wp_inbox_routes_identity_domain;
ALTER TABLE wp_inbox_routes ADD CONSTRAINT wp_inbox_routes_identity_domain CHECK (identity_kind IN ('phone', 'lid', 'bsuid', 'provider_user'));
ALTER TABLE wp_inbox_routes DROP CONSTRAINT IF EXISTS wp_inbox_routes_kind_domain;
ALTER TABLE wp_inbox_routes ADD CONSTRAINT wp_inbox_routes_kind_domain CHECK (kind IN ('allowlist', 'opt_in'));
ALTER TABLE wp_inboxes DROP CONSTRAINT IF EXISTS wp_inboxes_ai_mode_domain;
ALTER TABLE wp_inboxes DROP COLUMN IF EXISTS ai_mode, DROP COLUMN IF EXISTS phone_number_id;
DROP TABLE IF EXISTS wp_phone_numbers;
DROP TABLE IF EXISTS wp_wa_accounts;
ALTER TABLE wp_projects DROP CONSTRAINT IF EXISTS wp_projects_kind_domain;
ALTER TABLE wp_projects ADD CONSTRAINT wp_projects_kind_domain CHECK (kind IN ('automotive', 'service', 'internal'));
ALTER TABLE wp_projects DROP COLUMN IF EXISTS settings, DROP COLUMN IF EXISTS description;
DROP TABLE IF EXISTS wp_user_projects;
DROP TABLE IF EXISTS wp_users;
DELETE FROM wp_schema_migrations WHERE version = '0007_control_center';
