'use strict';
// =====================================================
// Mythos AI Executor — Free LLM Resources: catalog parser
// projects/mythos-ai-executor/free-llm/parser.js
//
// Pure function over the free-llm-api-resources README text (no fs, no
// network, no fetch) so it is fully offline-testable, following the same
// injection discipline as providers/openai-compat.js (transport) and
// personal-intelligence/runtime/openrouter-provider.js (transport).
//
// The upstream README is itself machine-generated ("DO NOT EDIT THIS
// FILE DIRECTLY. IT IS GENERATED BY src/pull_available_models.py"), so
// its per-provider block shape is stable: an H3 heading with an optional
// link, free-text notes, an optional **Limits:**/**Credits:** label, and
// EITHER an HTML <table> of {Model Name, Model Limits} OR one markdown
// bullet list of models (sometimes preceded by an unrelated notes bullet
// list — Mistral's "* requires phone verification" bullets before its
// "- model link" bullets is the reason the LAST bullet run, not the
// first, is treated as the model list).
//
// Everything extracted here is `source: 'free-llm-api-resources'`. A
// caller (sync.js) may overlay official-overrides.json, which always
// wins — this module never claims to be authoritative, only literal.
// =====================================================

var SECTION_CATEGORY = {
  'free providers': 'free',
  'providers with trial credits': 'trial'
};

function slugify(name) {
  return String(name).toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'provider';
}

function stripHtml(text) {
  return String(text)
    .replace(/<br\s*\/?>/gi, '; ')
    .replace(/<\/?[a-z][^>]*>/gi, '')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .trim();
}

function isPureHtmlTagLine(line) {
  return /^<\/?[a-z][a-z0-9]*>$/i.test(line.trim());
}

// [Text](url) -> {text, url}; plain text -> {text, url:null}
function parseLink(text) {
  var m = /^\[([^\]]+)\]\(([^)]+)\)$/.exec(text.trim());
  if (m) return { text: m[1].trim(), url: m[2].trim() };
  return { text: text.trim(), url: null };
}

// Finds every [text](url) occurrence in a line; returns the first, or
// null when the line has no markdown link at all.
function firstLink(text) {
  var m = /\[([^\]]+)\]\(([^)]+)\)/.exec(text);
  return m ? { text: m[1].trim(), url: m[2].trim() } : null;
}

// Best-effort literal API model slug, distinct from the human-readable
// display name the README shows. A deep link's URL path (OpenRouter:
// ".../google/gemma-3-12b-it:free") IS the real slug — 'link_derived'.
// A bullet/cell string with no whitespace (Cloudflare's
// "@cf/google/gemma-4-26b-a4b-it", Groq's "openai/gpt-oss-120b") usually
// already IS the real slug — 'literal_text'. A display-style name with
// spaces ("Llama 3.3 70B") is NOT the real slug and must never be sent
// to a provider's API as one — 'unconfirmed', api_model_id null. Never
// invented past what the source text actually shows.
// A deep link counts only when its path has the exact `org/model[:tag]`
// shape — two segments, no trailing slash, no query. A documentation link
// (Mistral's ".../getting-started/models/models_overview/") or a catalog
// page (".../models") is NOT a model, and treating it as one would hand
// the selector a slug that no provider accepts (found live 2026-09-16).
var MODEL_SLUG_PATH = /^[A-Za-z0-9][A-Za-z0-9._-]*\/[A-Za-z0-9][A-Za-z0-9._:-]*$/;

function deriveApiModelId(rawText, url) {
  if (url) {
    try {
      var seg = decodeURIComponent(String(url).replace(/^[a-z]+:\/\/[^/]+\//i, '').replace(/[?#].*$/, ''));
      if (seg && !/\s/.test(seg) && MODEL_SLUG_PATH.test(seg)) {
        return { api_model_id: seg, api_model_id_confidence: 'link_derived' };
      }
    } catch (e) { /* fall through */ }
  }
  if (rawText && !/\s/.test(rawText)) {
    return { api_model_id: rawText, api_model_id_confidence: 'literal_text' };
  }
  return { api_model_id: null, api_model_id_confidence: 'unconfirmed' };
}

function buildModel(name, url, limitsText) {
  var derived = deriveApiModelId(name, url);
  return {
    name: name,
    url: url || null,
    api_model_id: derived.api_model_id,
    api_model_id_confidence: derived.api_model_id_confidence,
    limits_text: limitsText || null,
    modality: guessModality(name)
  };
}

var MODEL_MODALITY_RULES = [
  [/whisper|speech.?to.?text|transcri/i, 'speech-to-text'],
  [/\btts\b|text.?to.?speech|orpheus/i, 'text-to-speech'],
  [/embedding/i, 'embedding'],
  [/guard|safeguard/i, 'moderation'],
  [/vision|vl\b/i, 'vision'],
  [/\breranker?\b/i, 'reranking']
];

// Heuristic only (§ docs/MYTHOS_FREE_LLM_RESOURCES.md "modality tagging
// is heuristic, non-authoritative") — the source list documents access,
// not modality.
function guessModality(modelName) {
  for (var i = 0; i < MODEL_MODALITY_RULES.length; i++) {
    if (MODEL_MODALITY_RULES[i][0].test(modelName)) return MODEL_MODALITY_RULES[i][1];
  }
  return 'chat';
}

var REQUIREMENT_RULES = [
  [/phone (?:number )?verification|phone.?verified/i, 'phone_verification'],
  [/credit card|payment method/i, 'payment_method'],
  [/opt(?:ing)? into data training|used for training/i, 'data_training_opt_in']
];

var DATA_POLICY_RULE = /data (?:is |will be |may be )?(?:used|training|improvement)/i;

function extractTable(block) {
  var m = /<table[^>]*>([\s\S]*?)<\/table>/i.exec(block);
  if (!m) return null;
  var rowRe = /<tr>\s*<td>([\s\S]*?)<\/td>\s*<td>([\s\S]*?)<\/td>\s*<\/tr>/gi;
  var rows = [];
  var rm;
  while ((rm = rowRe.exec(m[1])) !== null) {
    var name = stripHtml(rm[1]);
    var limits = stripHtml(rm[2]);
    if (/^model name$/i.test(name)) continue; // header row, defensive
    if (!name) continue;
    rows.push(buildModel(name, null, limits));
  }
  return { rows: rows, remainder: block.replace(m[0], '\n') };
}

// Splits a block's lines into runs of consecutive bullet lines
// (`- ` or `* `) separated by non-bullet lines. Returns
// { runs: [[line,...],...], nonBulletLines: [...] } — order preserved.
function splitBulletRuns(lines) {
  var runs = [];
  var nonBulletLines = [];
  var current = null;
  lines.forEach(function (line) {
    var isBullet = /^\s*[-*]\s+\S/.test(line);
    if (isBullet) {
      var text = line.replace(/^\s*[-*]\s+/, '');
      if (!current) { current = []; runs.push(current); }
      current.push(text);
    } else {
      current = null;
      if (line.trim()) nonBulletLines.push(line.trim());
    }
  });
  return { runs: runs, nonBulletLines: nonBulletLines };
}

function scanRequirementsAndPolicy(lines, requirementsSet, policyNotes) {
  lines.forEach(function (line) {
    if (isPureHtmlTagLine(line)) return;
    REQUIREMENT_RULES.forEach(function (rule) {
      if (rule[0].test(line)) requirementsSet[rule[1]] = true;
    });
    if (DATA_POLICY_RULE.test(line)) policyNotes.push(line.trim());
  });
}

// Parses one provider block's body (everything after the `### ` heading
// line, up to the next `### ` or end of section).
function parseProviderBody(body) {
  var requirementsSet = { signup: true }; // every listed service needs an account/key by construction
  var policyNotes = [];
  var limitsText = null;
  var limitsUrl = null;
  var creditsText = null;
  var models = [];

  var table = extractTable(body);
  var rest = table ? table.remainder : body;
  if (table) models = table.rows;

  var lines = rest.split('\n');
  var labelledRest = [];
  // "**Limits:**" (and, symmetrically, "**Models:**") sometimes has no
  // text on its own line — OpenRouter and Cohere both put the actual
  // [text](url) on the NEXT line instead. This flag carries the label
  // across that gap so the value still lands in the right field instead
  // of falling through into labelledRest as an unrelated note.
  var awaitingLimitsValue = false;

  function applyLimitsValue(text) {
    var t = text.trim();
    var link = firstLink(t);
    limitsUrl = link ? link.url : limitsUrl;
    limitsText = t ? stripHtml(t.replace(/\[|\]\([^)]*\)/g, '')) : limitsText;
  }

  lines.forEach(function (raw) {
    if (/^\s*[-*]\s+\S/.test(raw)) return; // bullets are handled by splitBulletRuns below, over the full line list
    var line = raw.trim();
    if (!line || isPureHtmlTagLine(line)) return;
    var limitsLabel = /^\*\*Limits(?:\s*\([^)]*\))?:\*\*\s*(.*)$/i.exec(line);
    var creditsLabel = /^\*\*Credits:\*\*\s*(.*)$/i.exec(line);
    var modelsLabel = /^\*\*Models:\*\*\s*(.*)$/i.exec(line);
    var reqLabel = /^\*\*Requirements:\*\*\s*(.*)$/i.exec(line);
    if (awaitingLimitsValue) {
      awaitingLimitsValue = false;
      applyLimitsValue(line);
      return;
    }
    if (limitsLabel) {
      var lv = limitsLabel[1].trim();
      if (lv) applyLimitsValue(lv);
      else awaitingLimitsValue = true;
      return;
    }
    if (creditsLabel) {
      creditsText = creditsLabel[1].trim() || creditsText;
      return;
    }
    if (reqLabel) {
      scanRequirementsAndPolicy([reqLabel[1]], requirementsSet, policyNotes);
      return;
    }
    if (modelsLabel && modelsLabel[1].trim()) {
      // Inline "**Models:** text" with no bullets, e.g. "Jamba family of models".
      var mlink = firstLink(modelsLabel[1]);
      models.push(buildModel(mlink ? mlink.text : modelsLabel[1].trim(), mlink ? mlink.url : null, null));
      return;
    }
    labelledRest.push(line);
  });

  if (!table) {
    // Split over the FULL line list (not a pre-filtered bullet-only
    // list) so a blank line or a **Limits:**-style label between two
    // bullet groups still breaks them into separate runs — this is what
    // lets Mistral's "* requires phone verification" notes stay out of
    // its "- model link" list.
    var split = splitBulletRuns(lines);
    if (split.runs.length) {
      var modelRun = split.runs[split.runs.length - 1];
      models = modelRun.map(function (text) {
        var link = parseLink(text);
        return buildModel(link.text, link.url, null);
      });
      split.runs.slice(0, -1).forEach(function (run) {
        scanRequirementsAndPolicy(run, requirementsSet, policyNotes);
      });
    }
  }

  scanRequirementsAndPolicy(labelledRest, requirementsSet, policyNotes);

  return {
    limits_text: limitsText,
    limits_url: limitsUrl,
    credits_text: creditsText,
    requirements: Object.keys(requirementsSet).sort(),
    data_policy_note: policyNotes.length ? policyNotes.join(' ') : null,
    notes: labelledRest.length ? labelledRest.join(' ') : null,
    models: models
  };
}

function parseSection(sectionText, category) {
  var blocks = sectionText.split(/\n### /).slice(1);
  return blocks.map(function (raw) {
    var nlIdx = raw.indexOf('\n');
    var headingLine = (nlIdx === -1 ? raw : raw.slice(0, nlIdx)).trim();
    var body = nlIdx === -1 ? '' : raw.slice(nlIdx + 1);
    var link = parseLink(headingLine);
    var parsed = parseProviderBody(body);
    return Object.assign({
      id: slugify(link.text),
      name: link.text,
      homepage: link.url,
      category: category,
      access_type: category === 'trial' ? 'trial' : 'free_tier',
      source: 'free-llm-api-resources'
    }, parsed);
  });
}

// parseCatalog(markdown) -> { free: [...], trial: [...] }
function parseCatalog(markdown) {
  var text = String(markdown || '').replace(/\r\n/g, '\n');
  var sections = text.split(/\n## /).slice(1);
  var out = { free: [], trial: [] };
  sections.forEach(function (raw) {
    var nlIdx = raw.indexOf('\n');
    var title = (nlIdx === -1 ? raw : raw.slice(0, nlIdx)).trim().toLowerCase();
    var category = SECTION_CATEGORY[title];
    if (!category) return; // unknown section (e.g. a future TOC change) — skip rather than guess
    var body = nlIdx === -1 ? '' : raw.slice(nlIdx + 1);
    out[category] = parseSection(body, category);
  });
  return out;
}

module.exports = {
  parseCatalog: parseCatalog,
  slugify: slugify,
  guessModality: guessModality,
  deriveApiModelId: deriveApiModelId
};
